### ISSUE TITLE
[逐影追星]: 增加夜间模式

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#100]
增加夜间模式更亲近~

scuplus_version: 0.7.0
手机: HUAWEI-VTR-AL00-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个工作量比较大，后期再进行完善
可以添加用户交流、反馈群: 698433701
