### ISSUE TITLE
[Lithoponee]: 账号

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#101]
账号不能绑定

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 11.2.2 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请绑定统一认证中心的账号也就是 my.scu.edu.cn 的账号密码不是，教务处的哦
可以添加用户交流、反馈群: 698433701

**Comment by scuplus** [comment]
每次显示绑定了，可首页还是无法显示   $$$Lithoponee

**Comment by mohuishou** [comment]
请退出小程序（后台关闭）然后再试试呢？目前的确有一定几率出现这个bug
可以添加用户交流、反馈群: 698433701

**Comment by scuplus** [comment]
好哒，谢谢您！😘   $$$Lithoponee

**Comment by mohuishou** [comment]
不用谢，觉得还不错的话帮忙宣传一下哦

**Comment by scuplus** [comment]
👌🏿 

   $$$Lithoponee

**Comment by mohuishou** [comment]
ok，这个问题关闭了
可以添加用户交流、反馈群: 698433701
