### ISSUE TITLE
[等你下课]: 课程表出错

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#102]
我选修的一门课程第五周是没有课的，但是小程序课程表是显示的有课，希望查看一下。那节课是周六上午的课。

scuplus_version: 0.7.0
手机: vivo-vivo X9i-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，请添加用户交流、反馈群: 698433701 反馈一下截图，这个需要定点排查一下

**Comment by scuplus** [comment]
好的   $$$等你下课
