### ISSUE TITLE
[上天入地小林子]: 课表显示不全

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#103]
周四第一节课表显示不了
还有建议反馈栏增添传图功能，也方便信息描述

scuplus_version: 0.7.0
手机: iPhone-iPhone 6<iPhone7,2>-iOS 11.2.6 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个功能已经在排期当中了
可以添加用户交流、反馈群: 698433701
