### ISSUE TITLE
[七百是棵麦子]: 什么都显示不出来

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#104]
绑定成功，什么都没有，校园卡也没有内容，课表也没有内容

scuplus_version: 0.7.0
手机: iPhone-iPhone 6<iPhone7,2>-iOS 11.2.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据。
可以添加用户交流、反馈群: 698433701
