### ISSUE TITLE
[皮卡皮卡皮卡皮～€～]: 无法绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#105]
无法绑定

scuplus_version: 0.7.0
手机: HONOR-BKL-AL20-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请绑定统一认证中心的账号也就是 my.scu.edu.cn 的账号密码不是，教务处的哦
可以添加用户交流、反馈群: 698433701

**Comment by scuplus** [comment]
噢噢好的我试试～(｡･ω･｡)ﾉ♡   $$$皮卡皮卡皮卡皮～€～
