### ISSUE TITLE
[魏鑫]: 咨询栏最上面有一条被遮住了

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#106]
如题，建议反馈的时候可以插图

scuplus_version: 0.7.0
手机: OnePlus-ONEPLUS A3000-Android 8.1.0 
微信：6.6.2,SDK: 1.9.97

**Comment by mohuishou** [comment]
可以在群里反馈截图，目前反馈功能暂时不支持截图，感谢你的反馈，这个的确需要截图才行
可以添加用户交流、反馈群: 698433701
