### ISSUE TITLE
[斯琴]: 我有借阅哦

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#108]
我有借阅但是显示没有

scuplus_version: 0.7.0
手机: HUAWEI-EVA-AL10-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
目前无法通过统一认证中心访问图书馆数据，所以借阅相关功能暂时无法使用。
下一个小版本会修复这个问题，添加单独的图书馆账号绑定
感谢你的反馈，可以添加用户交流、反馈群: 698433701
