### ISSUE TITLE
[咖啡茶组]: 有些小问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#109]
在下方的考表及图书借阅不可用
但上面的同功能的圆形按钮可以使用

scuplus_version: 0.7.0
手机: OPPO-OPPO R11-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
目前无法通过统一认证中心访问图书馆数据，所以借阅相关功能暂时无法使用。
下一个小版本会修复这个问题，添加单独的图书馆账号绑定
考表可能是本身没有数据
感谢你的反馈，可以添加用户交流、反馈群: 698433701
