### ISSUE TITLE
[请输入用户名]: 课表

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#110]
通过点击课表上的某一堂课  可以查看到 上课时间、任课老师等详细信息 谢谢

scuplus_version: 0.7.0
手机: HUAWEI-VKY-TL00-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个考虑在后面的版本实现。
可以添加用户交流、反馈群: 698433701
