### ISSUE TITLE
[Reina]: 一卡通没有数据

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#111]
我的账号2015141021098，访问一卡通没有数据，麻烦您们看看。
你们辛苦啦！！！优秀！

scuplus_version: 0.7.0
手机: iPhone-iPhone 7<iPhone9,1>-iOS 10.0.2 
微信：6.6.6,SDK: 1.9.97

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据。感谢你的反馈，如果觉得不错可以帮忙安利一下
可以添加用户交流、反馈群: 698433701
