### ISSUE TITLE
[醉离_ZCY]: 建议课表能自己添加课程

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#112]
有很多习题课之类的课需要自己手动添加，请采纳~

scuplus_version: 0.7.0
手机: Meizu-M3X-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个功能目前来说比较复杂会放到后面实现
可以添加用户交流、反馈群: 698433701
