### ISSUE TITLE
[hungrybaby]: 一卡通

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#113]
一卡通充值之后使用没有数据更新喃

scuplus_version: 0.7.0
手机: OPPO-OPPO R7sm-Android 5.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据。
可以添加用户交流、反馈群: 698433701
