### ISSUE TITLE
[醉离_ZCY]: 建议课表上方显示日期

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#114]
只显示周数而不显示日期，有一点不方便。

scuplus_version: 0.7.0
手机: Meizu-M3X-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个需求考虑一下实现，如果可以会在下个版本实现
感谢你的反馈，可以添加用户交流、反馈群: 698433701
