### ISSUE TITLE
[孙珏寒]: 能不能添加一个可以查询课程号的功能呀

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#115]
能不能添加一个可以查询课程号的功能呀

scuplus_version: 0.7.0
手机: OnePlus-ONEPLUS A5000-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这功能会在0.8.0版本实现，会上线一个完整的课程助手
感谢你的反馈，可以添加用户交流、反馈群: 698433701

**Comment by scuplus** [comment]
🌹    $$$孙珏寒

**Comment by mohuishou** [comment]
如果觉得不错的话可以安利一下

**Comment by scuplus** [comment]
完全可以   $$$孙珏寒

**Comment by mohuishou** [comment]
感谢感谢
可以添加用户交流、反馈群: 698433701，后期会招募少量内测体验用户
