### ISSUE TITLE
[]: 修改密码

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#116]
建议可以修改密码

scuplus_version: 0.7.0
手机: Xiaomi-MI 5s-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
密码修改可以到 my.scu.edu.cn 修改再到We川大重新绑定，感谢你的反馈
可以添加用户交流、反馈群: 698433701
