### ISSUE TITLE
[走乂又土化十]: 无法绑定帐号

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#117]
无法绑定帐号

scuplus_version: 0.7.0
手机: HUAWEI-EVA-AL10-Android 7.0 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
1. 如果反馈账号密码错误请使用 my.scu.edu.cn 的账号密码而不是教务处的。可以到这个网站上修改重置密码
2. 如果绑定之后直接跳转页面，说明绑定成功，但是进入功能页面仍然需要绑定，请退出小程序(后台关闭进程)重新进入
可以添加用户交流、反馈群: 698433701
