### ISSUE TITLE
[常青]: 没有课表信息

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#118]
填过学号密码了噻，没有课表，校园卡信息呀

scuplus_version: 0.7.0
手机: OPPO-OPPO A57t-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据。
可以添加用户交流、反馈群: 698433701
