### ISSUE TITLE
[早睡]: 我的we川大没有校园资讯（学工部等网站）板块

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#119]
我是物理学院的

scuplus_version: 0.7.0
手机: HONOR-STF-AL00-Android 8.0.0 
微信：6.6.3,SDK: 1.9.97

**Comment by scuplus** [comment]
鹅妈妈密密麻麻……提交错了对不起哈。有的，真的不好意思。。。   $$$早睡

**Comment by mohuishou** [comment]
ok，那关闭问题了
可以添加用户交流、反馈群: 698433701
