### ISSUE TITLE
[Mr.Z]: 校历

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#120]
下学期开学时间没得

scuplus_version: 0.7.0
手机: HONOR-BND-AL10-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
目前暂时只支持本学期校历，感谢你的反馈。这个功能考虑后期实现
可以添加用户交流、反馈群: 698433701
