### ISSUE TITLE
[Camellia 杨尧]: 校园卡充值

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#121]
充值校园卡，可以用微信、支付宝转账。

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 11.2.6 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的建议，这个功能目前来看无法实现，这个需要学校官方来做
可以添加用户交流、反馈群: 698433701
