### ISSUE TITLE
[Dobby]: 无数据

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#122]
输入密码登录成功后没有任何数据，但是点开比如说课表会显示获取成功

scuplus_version: 0.7.0
手机: OPPO-OPPO R9s-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据。新用户目前不会主动出发数据更新
可以添加用户交流、反馈群: 698433701
