### ISSUE TITLE
[~_^]: 希望课表可以自己编辑

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#124]
有的课教务处并不显示，希望可以自己编辑课表

scuplus_version: 0.7.0
手机: iPhone-iPhone 6<iPhone7,2>-iOS 11.1.2 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个工作量稍微比较大，只有往后延续一点了
可以添加用户交流、反馈群: 698433701
