### ISSUE TITLE
[Kabosu]: 身份证最后一位为x

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#126]
登不进去

scuplus_version: 0.7.0
手机: iPhone-iPhone 7<iPhone9,1>-iOS 10.3.2 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
1. 如果反馈账号密码错误请使用 my.scu.edu.cn 的账号密码而不是教务处的。可以到这个网站上修改重置密码
可以添加用户交流、反馈群: 698433701
