### ISSUE TITLE
[lw]: 标签不能点

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#133]
资讯内容里头的标签按钮点不下去 没办法读取到关键词

scuplus_version: 0.7.0
手机: iPhone-iPhone 7<iPhone9,1>-iOS 10.3.2 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
列表页可以点击，详情目前还不支持
感谢你的反馈，可以添加用户交流、反馈群: 698433701
