### ISSUE TITLE
[子时渡川]: 信息获取失败

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#138]
可能因为不同网站的密码不同，绑定的密码无法用于获取课表信息

scuplus_version: 0.7.0
手机: OPPO-OPPO R9s-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by scuplus** [comment]
已解决   $$$子时渡川

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据。请问具体报错信息？
可以添加用户交流、反馈群: 698433701

**Comment by mohuishou** [comment]
好的，如果觉得不错的话，帮忙按理一下吧
问题关闭了
可以添加用户交流、反馈群: 698433701
