### ISSUE TITLE
[皮皮玥]: 11

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#139]
建议增设二级密码 因为可能手机借给同学的话通过微信他可以很方便的获取到我们的个人信息

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 10.3.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个可以考虑一下。不过有这种情况建议直接给微信等APP上锁，因为微信上的私人信息更多
感谢你的反馈，可以添加用户交流、反馈群: 698433701

**Comment by scuplus** [comment]
ios系统该怎么上锁……   $$$皮皮玥

**Comment by mohuishou** [comment]
(⊙o⊙)…这个我也不太清楚，可以用搜索引擎搜一下，我用的小米自带有这个功能0.0
感谢你的反馈，可以添加用户交流、反馈群: 698433701
