### ISSUE TITLE
[Hedy]: 优化功能

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#141]
希望一卡通可以使用手机代替刷卡功能，并且手机可以显示一卡通的图样这样进出校门就不用再急急忙忙掏学生卡了

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 11.2.6 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个功能我也想做，但是这个只能靠学校实现了，牵扯诸如硬件修改之类的问题
可以添加用户交流、反馈群: 698433701

**Comment by scuplus** [comment]
没办法和学校争取然后进行合作吗
对于什么硬件软件的我不太懂，我只是从使用者一方出发，希望能有这样的功能可以更加方便😂😂   $$$Hedy

**Comment by mohuishou** [comment]
现在还在申请和学校合作，但是不知道能不能成
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
