### ISSUE TITLE
[哈徒弟]: 课表有问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#143]
课表有课，但显示我无课

scuplus_version: 0.7.0
手机: iPhone-iPhone 6 Plus<iPhone7,1>-iOS 11.2.6 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
初次使用没有数据：
请在相应页面手动下拉刷新一下数据。
可以添加用户交流、反馈群: 698433701
