### ISSUE TITLE
[东野🌚]: 课程表是空的

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#145]
导入课程表之后是空的😂 

scuplus_version: 0.7.0
手机: HUAWEI-HUAWEI MLA-AL10-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据。
可以添加用户交流、反馈群: 698433701
