### ISSUE TITLE
[林风絮]: 图书馆借阅数据刷不出来？

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#146]
Rt

scuplus_version: 0.7.0
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.2.1 
微信：6.6.1,SDK: 1.9.9

**Comment by scuplus** [comment]
不好意思我看到说明了   $$$林风絮

**Comment by mohuishou** [comment]
下一个小版本会修复这个问题，添加单独的图书馆账号绑定
感谢你的反馈，可以添加用户交流、反馈群: 698433701
