### ISSUE TITLE
[诺伊斯梅克]: 一卡通消费错误

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#147]
川大服务那个消费延迟了一天，那个数据被直接拿过来了 比如我4.2号消费了100块，这个小程序显示的是4.3号消费了100块

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 10.3.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个暂时无解，因为小程序抓取的就是那个的数据
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
