### ISSUE TITLE
[黑笔星星]: 一卡通消费记录时间错位

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#148]
因为数据是前一天的，所以流水信息应该显示前一天，不是今天的。就是现在的流水信息里，日期应该减一天

scuplus_version: 0.7.0
手机: xiaomi-Redmi Note 4X-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
如果所有的数据都是这样，下个版本修复一下
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
