### ISSUE TITLE
[甜甜圈🙆]: 课表

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#150]
希望添加一个添加课程的功能。这样的话二专的课就可以手动输入了。

scuplus_version: 0.7.0
手机: HONOR-BLN-AL20-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个工作量稍微比较大，只有往后延续一点了
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
