### ISSUE TITLE
[诺伊斯梅克]: 看完bug反馈

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#151]
看完bug反馈怎么返回到小程序主页面啊 只能重开微信吗

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 10.3.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
上面三个点，点击一下，有返回首页
