### ISSUE TITLE
[双层皇冠堡]: App

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#153]
可以说做成手机App吗 ，这样的话会更棒。不过依然感谢你们对这个产品的努力，幸苦了！

scuplus_version: 0.7.0
手机: iPhone-iPhone X (GSM+CDMA)<iPhone10,3>-iOS 11.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，目前没有精力诶，目前这个小程序只有我一个人，所有暂时无法开发app
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
