### ISSUE TITLE
[alpha not bet]: 主页面无内容

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#154]
主页面显示一个不高兴脸，一直无内容

scuplus_version: 0.7.0
手机: OnePlus-ONEPLUS A3000-Android 8.0.0 
微信：6.6.2,SDK: 1.9.97

**Comment by mohuishou** [comment]
提供一个临时解决方案，你试一下在微信小程序里面直接删除小程序，然后重新搜索添加呢？
欢迎加入We川大用户交流，群聊号码：698433701

**Comment by scuplus** [comment]
解决了，谢谢啦   $$$字母表

**Comment by mohuishou** [comment]
不客气，觉得还不错的话，就帮忙安利一下吧，问题关闭了
