### ISSUE TITLE
[星屑papa]: 已绑定账号但每次进入我的账号就要重新绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#156]
没有学生卡消费信息，也没有课表～麻烦啦

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 11.2.5 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
如果绑定之后直接跳转页面，说明绑定成功，但是进入功能页面仍然需要绑定，请退出小程序(后台关闭进程)重新进入
欢迎加入We川大用户交流，群聊号码：698433701
