### ISSUE TITLE
[blank]: 信息未获取

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#157]
图书借阅的信息刷不出来

scuplus_version: 0.7.0
手机: HUAWEI-VTR-AL00-Android 8.0.0 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
借阅问题：目前无法通过统一认证中心访问图书馆数据，所以借阅相关功能暂时无法使用。
下一个小版本会修复这个问题，添加单独的图书馆账号绑定
希望大家多多分享给你的同学朋友们
