### ISSUE TITLE
[Q.2]: 能否在we川大上加入失物招领的功能呢

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#158]
就现在we川大的表现来看，它完全拥有替代课程格子之类产品的能力，只要得到宣传就能有很大的使用量，而再此基础，其实可以加入一个失物招领的功能，捡到的同学可以登记捡到失物和相关信息，失主也可以快速查询是否有人捡到自己的东西。现在的失物招领群其实效果不佳，很难找到自己想要的讯息。

scuplus_version: 0.7.0
手机: HONOR-DUK-AL20-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个功能其实有考虑，不过排期稍微靠后，只有有一定的用户量了，才有意义
欢迎加入We川大用户交流，群聊号码：698433701
