### ISSUE TITLE
[大宝离不开SOD蜜]: 登陆问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#159]
iOS 系统学号输入了但是系统一直显示没有输入

scuplus_version: 0.7.0
手机: iPhone-iPhone 7 Plus<iPhone9,2>-iOS 10.3.2 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
可以添加用户交流、反馈QQ群: 698433701 反馈一下具体截图么
