### ISSUE TITLE
[H2]: 添课功能

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#161]
希望可以加一个自己添课的功能，因为有一些习题课在课表上没有预置

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 10.3.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个工作量稍微比较大，只有往后延续一点了
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
