### ISSUE TITLE
[顾昀]: 对于不同功能对应的功能区块

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#162]
可以改成区块可以拖动 删除 移动。比如下面的缩小的一卡通信息 和课表信息 可以改变排版的顺序 增加或删除一些这种面板

scuplus_version: 0.7.0
手机: HUAWEI-MHA-AL00-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个功能有考虑过，但是目前来说在小程序还比较难以实现，目前以功能开发为主，这个会在后期优化上加上的
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701

**Comment by scuplus** [comment]
好的！！！   $$$顾昀

**Comment by mohuishou** [comment]
问题关闭了
