### ISSUE TITLE
[BRONCHO]: 校车

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#163]
你好，我建议校车查询页面的的「始发地」和「目的地」能够通过中间的箭头对调位置，相信会在一定程度上方便用户的使用，希望采纳！

scuplus_version: 0.7.0
手机: iPhone-iPhone X (GSM+CDMA)<iPhone10,3>-iOS 11.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个考虑会在下个版本添加的
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
