### ISSUE TITLE
[嗷嗷嗷嗷酱、]: 一个小小的提议

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#165]
希望能把宿舍的网上报修系统也包含进来呀、
感谢飞扬设计了这么好的小程序、😊

scuplus_version: 0.7.0
手机: OPPO-OPPO R11-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个后面会添加的，排期暂时没有确定
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
