### ISSUE TITLE
[胡云云云云]: 没有数据显示

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#166]
绑定账号后可以看到一卡通数据，成绩数据但是看不到课程表数据

scuplus_version: 0.7.0
手机: HONOR-BND-AL00-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据。
可以添加用户交流、反馈群: 698433701
