### ISSUE TITLE
[Le vent]: 全部信息为空

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#167]
我绑定了个人信息。但是课程表，成绩，校园卡的信息都为空，不知道是怎么回事哎

scuplus_version: 0.7.0
手机: Xiaomi-Mi Note 3-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
初次使用没有数据：
请在相应页面手动下拉刷新一下数据。
可以添加用户交流、反馈群: 698433701
