### ISSUE TITLE
[冰上的月光]: 首页点不开

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#169]
首页点不开 出来是个哭脸的形式

scuplus_version: 0.7.0
手机: iPhone-iPhone X (GSM+CDMA)<iPhone10,3>-iOS 11.2.6 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
提供一个临时解决方案，你试一下在微信小程序里面直接删除小程序，然后重新搜索添加呢？
欢迎加入We川大用户交流，群聊号码：698433701
