### ISSUE TITLE
[烛光]: 课程表界面

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#170]
课程表点开后，能够不滑动，一页显示全课表比较好

scuplus_version: 0.7.0
手机: nubia-NX563J-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个还在考虑优化当中，主要是有的课程名太长放不下，如果能够做下个小版本就能上线
