### ISSUE TITLE
[我想你像蜜一样甜]: 充值一卡通

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#171]
各位牛逼的小姐姐小哥哥 考虑一下增加一个充值的功能呗

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 11.2.2 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个目前来看，还不能实现，这个需要学校官方来做
