### ISSUE TITLE
[BRONCHO]: 通知

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#172]
你好，我建议「通知」小组件可以增加「添加/删除/排序」的功能，谢谢。

scuplus_version: 0.7.0
手机: iPhone-iPhone X (GSM+CDMA)<iPhone10,3>-iOS 11.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个功能在小程序里面实现比较麻烦，但是已经在尝试过
