### ISSUE TITLE
[夏之木]: 建议增加校历的“备注”功能

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#173]
建议增加校历的“备注”功能，便于我将要做的事和课程相结合，合理安排，谢谢！

scuplus_version: 0.7.0
手机: Xiaomi-MI 4LTE-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
目前主要稳定功能，以及添加常用功能，这个功能之后考虑
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
