### ISSUE TITLE
[米丝某洁]: 希望增添edu邮箱功能

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#177]
就是，因为edu邮箱不太方便实时收发邮件，如果能借这个平台实时查看会更方便。

scuplus_version: 0.7.0
手机: Xiaomi-MI 5s-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，暂时不考虑支持邮箱功能，邮箱建议直接使用手机自带邮箱app或者是qq邮箱。
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
