### ISSUE TITLE
[こししん]: 什么数据都查不到

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#178]
查不到任何数据，刷新咯了也没用

scuplus_version: 0.7.0
手机: vivo-vivo X20A-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请问你是本科同学还是研究生同学呢

**Comment by mohuishou** [comment]
目前研究生教务信息还未适配，暂时只能使用一卡通功能
