### ISSUE TITLE
[gwdry]: 一卡通

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#179]
反应超慢，昨天的消费今天都有没更新

scuplus_version: 0.7.0
手机: iPhone-iPhone SE<iPhone8,4>-iOS 11.2.6 
微信：6.6.6,SDK: 1.9.97

**Comment by mohuishou** [comment]
请在相应页面手动下拉刷新一下数据，这个数据同步于http://ecard.scu.edu.cn  只有这里有数据了We川大才能获取到哦
可以添加用户交流、反馈群: 698433701

**Comment by mohuishou** [comment]
问题已经找到，从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，如果下周还无法访问再考虑实现单独绑定机制
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
