### ISSUE TITLE
[k_l😶]: 课程表和一卡通

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#181]
刷新不出来

scuplus_version: 0.7.0
手机: HONOR-BLN-AL10-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
是只有这两个刷新不出来么，还是所有的比如成绩也无法获取呢，请问反馈的信息是什么呢

**Comment by scuplus** [comment]
就是点进去是空白的   $$$k_l😶

**Comment by mohuishou** [comment]
下拉刷新试试呢

**Comment by scuplus** [comment]
一卡通还是不行   $$$k_l😶

**Comment by mohuishou** [comment]
问题已经找到，从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，如果下周还无法访问再考虑实现单独绑定机制
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
