### ISSUE TITLE
[回不去的时光]: 校园卡流水

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#182]
emmm只能查两天前的嘛。。。有没有即时的。。

scuplus_version: 0.7.0
手机: HONOR-PRA-AL00-Android 7.0 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个数据同步于http://ecard.scu.edu.cn 只有这里有数据了We川大才能获取到哦
可以添加用户交流、反馈群: 698433701
