### ISSUE TITLE
[我一直很饿]: 首页没有内容

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#185]
只有一张难过脸表情，没法下拉刷新

scuplus_version: 0.7.0
手机: Xiaomi-Redmi 4-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个问题已经修复了，不过新版本发布要等到清明节之后了，提供一个临时解决方案，先删除小程序再重新搜索进入一下，感谢你的反馈

**Comment by mohuishou** [comment]
新版本已发布，可以退出重进试试
