### ISSUE TITLE
[江安扛把子🌟]: 显示绑定成功但没有绑定上

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#189]
将学号密码输入显示绑定成功 但没有绑定上

scuplus_version: 0.7.0
手机: iPhone-iPhone 6 Plus<iPhone7,1>-iOS 10.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
新版本会解决这个问题，目前临时解决方案是，后台退出小程序，重新进入应该就可以了

**Comment by mohuishou** [comment]
新版本已发布，可以退出重进试试
