### ISSUE TITLE
[大白]: 校园卡

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#190]
校园卡消费不更新

scuplus_version: 0.7.0
手机: Xiaomi-MI 4LTE-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请问下拉刷新之后反馈的具体信息
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701

**Comment by mohuishou** [comment]
问题已经找到，从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，如果下周还无法访问再考虑实现单独绑定机制
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
