### ISSUE TITLE
[eto]: 一卡通信息？

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#192]
为啥一卡通信息刷不出来？

scuplus_version: 0.7.0
手机: Meizu-MX6-Android 7.1.1 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
请问下拉刷新之后反馈的具体信息
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701

**Comment by scuplus** [comment]
下拉之后啥都没有刷出来   $$$eto

**Comment by scuplus** [comment]
下拉之后啥都没有刷出来   $$$eto

**Comment by mohuishou** [comment]
加一下用户qq群，私聊一下我吧，我是群主。反馈QQ群: 698433701

**Comment by scuplus** [comment]
得行   $$$eto

**Comment by mohuishou** [comment]
ok

**Comment by scuplus** [comment]
竟然不是AI   $$$eto

**Comment by mohuishou** [comment]
0.0 肯定不是啊

**Comment by mohuishou** [comment]
问题已经找到，从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，如果下周还无法访问再考虑实现单独绑定机制
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701

**Comment by scuplus** [comment]
好的，谢谢(*/ω＼*)   $$$eto
