### ISSUE TITLE
[大圣]: 一卡通

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#193]
一卡通的相关内容不显示，刷新之后还是不显示

scuplus_version: 0.7.0
手机: HONOR-DUK-AL20-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
添加用户交流、反馈群: 698433701反馈一下详细信息，谢谢

**Comment by mohuishou** [comment]
问题已经找到，从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，如果下周还无法访问再考虑实现单独绑定机制
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
