### ISSUE TITLE
[G~W]: 首页什么都没有  空白

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#195]
首页啥都没有😭

scuplus_version: 0.7.0
手机: vivo-vivo X9-Android 7.1.2 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个问题已经修复了，不过新版本发布要等到清明节之后了，提供一个临时解决方案，先删除小程序再重新搜索进入一下，感谢你的反馈
