### ISSUE TITLE
[青峰塾]: 课程表

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#196]
课程表的界面实在是太不走心了  

scuplus_version: 0.7.0
手机: OPPO-OPPO R11st-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
已经优化了，新版本在等待审核

**Comment by mohuishou** [comment]
已经发布了，后台退出重进一下
