### ISSUE TITLE
[墨]: 主页

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#197]
主页怎么加载不出来呢？

scuplus_version: 0.7.0
手机: Xiaomi-MI 6-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
退出重新进入一下呢，刚刚发布了新版本，欢迎加入We川大用户交流，群聊号码：698433701

**Comment by mohuishou** [comment]
不用谢，觉得不错的话就帮忙安利一下吧，问题关闭了
