### ISSUE TITLE
[一姑娘]: 无数据

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#199]
登陆之后，校园卡和课表都没有数据，别的没看，估计也没有

scuplus_version: 0.7.1
手机: iPhone-iPhone 6<iPhone7,2>-iOS 11.2.6 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请问你绑定成功没呢，还有就是请问你是本科同学还是研究生同学呢，目前we川大还没有适配到研究生同学的教务系统，如果是本科同学请在相应的页面下拉刷新试试呢

**Comment by scuplus** [comment]
绑定成功了，是本科生，每次下拉都显示获取信息成功，但是还是没有，我发现成绩单和图书馆信息是有的，但是校园卡和课表一直没有   $$$一姑娘

**Comment by mohuishou** [comment]
添加一下QQ群私聊一下群主吧，这个需要排查一下，欢迎加入We川大用户交流，群聊号码：698433701

**Comment by mohuishou** [comment]
对了，还可以试试后台退出小程序重新进入看看

**Comment by mohuishou** [comment]
一卡通是已知问题，因为目前无法通过统一认证平台访问一卡通查询系统，课程表需要排查一下
