### ISSUE TITLE
[恬淡相随]: 加权平均分/绩点计算方式

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#201]
形势与政策每学期学分为0.25，希望能考虑到这一点，做出更准确的计算

scuplus_version: 0.7.1
手机: 360-1801-A01-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个考虑后期加上
