### ISSUE TITLE
[桑]: 课程表和成绩无法显示

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#203]
进入课程表和成绩刷新了也没有内容

scuplus_version: 0.7.1
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 11.0.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
刷新显示的反馈信息是什么呢

**Comment by scuplus** [comment]
没有获取课程表数据，成绩是 更新失败   $$$桑

**Comment by mohuishou** [comment]
请问你是本科同学还是研究生同学呢，目前we川大还没有适配到研究生同学的教务系统，如果是本科同学请在用户qq群私聊一下群主，反馈一下截图。用户交流、反馈QQ群: 698433701

**Comment by scuplus** [comment]
啊原来如此，我是研究生同学，希望以后能更新到～   $$$桑

**Comment by mohuishou** [comment]
这个会的，后面会添加到的，感谢你的反馈

**Comment by scuplus** [comment]
嗯嗯好的，感谢你们的辛苦付出   $$$桑

**Comment by mohuishou** [comment]
不用谢，问题关闭了哦
