### ISSUE TITLE
[世离先生]: 校园卡余额不更新

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#206]
刚绑定的时候有交易流水，之后就没有实时更新了

scuplus_version: 0.7.1
手机: vivo-vivo X20A-Android 7.1.1 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，如果下周还无法访问再考虑实现单独绑定机制
感谢你的反馈
