### ISSUE TITLE
[boom]: 课程表时间错误

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#209]
现在周一，课程表提示的今日课程却是周日的课程。

scuplus_version: 0.7.1
手机: honor-FRD-AL00-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，可以加群反馈一下详细信息和截图么用户交流、反馈QQ群: 698433701

**Comment by mohuishou** [comment]
bug已修复，新版本已发布，如果发现没有更新，请后台退出小程序重新进入
