### ISSUE TITLE
[林某某]: 课程表

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#210]
首页显示当天课程有误

scuplus_version: 0.7.1
手机: HONOR-DUK-AL20-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，可以加群反馈一下详细信息和截图么用户交流、反馈QQ群: 698433701

**Comment by mohuishou** [comment]
新版本已发布，如果发现没有更新，请后台退出小程序重新进入
