### ISSUE TITLE
[LANYAa]: 无法绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#214]
输入了学号和密码显示用户不存在或密码错误，但是我没输错😭😭😭

scuplus_version: 0.7.1
手机: OPPO-OPPO R9m-Android 5.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
如果出现可以登录上面的网站但是无法绑定，可以加用户QQ群联系群主，欢迎加入We川大用户交流，群聊号码：698433701

**Comment by scuplus** [comment]
好的好的，谢谢你啦!   $$$LANYAa

**Comment by mohuishou** [comment]
没事，感谢你的反馈，问题关闭了哦
