### ISSUE TITLE
[毛伟平]: 自习查询可以隔天查询吗

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#215]
自习空教室查询能看未来几天的就好了

scuplus_version: 0.7.1
手机: iPhone-iPhone 7 Plus<iPhone9,2>-iOS 10.3.1 
微信：6.6.6,SDK: 1.9.98

**Comment by mohuishou** [comment]
暂时不可以诶，目前自习查询都是比较准确的，未来几天的暂时没找到查询接口，而且也不能保证准确性
