### ISSUE TITLE
[浅]: 课表设置

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#216]
课表可以设置每一节课的时间段就更好啦，更清晰明了，谢谢

scuplus_version: 0.7.1
手机: xiaomi-Redmi Note 5A-Android 7.1.2 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个没有做的主要原因是不同校区的时间不一致，这个还在准备当中

**Comment by scuplus** [comment]
嗯嗯，麻烦了   $$$浅

**Comment by mohuishou** [comment]
感谢你的反馈，如果觉得We川大不错的话，就帮忙安利一下吧，转发到年级QQ/微信群之类的，感谢
