### ISSUE TITLE
[斯坦尼斯拉夫斯基]: 体测预约查询功能

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#218]
这个小程序很棒，可以考虑把体育学院的体测预约查询整合进来，有个公众号叫川大体协，上面有的功能集成到这里就很方便了

scuplus_version: 0.7.1
手机: HONOR-STF-AL00-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这个需要有账号测试，可以添加用户QQ群，欢迎加入We川大用户交流，群聊号码：698433701
