### ISSUE TITLE
[我爱学习]: 星期数搞错了

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#220]
今天星期二，但是今日课表上显示的星期一的课表

scuplus_version: 0.7.1
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.2.6 
微信：6.6.6,SDK: 1.9.98

**Comment by mohuishou** [comment]
感谢你的反馈，bug已经修复了但是要今天晚上或者明天才能发布新版本，版本审核需要时间

**Comment by scuplus** [comment]
好的好的谢谢   $$$我爱学习

**Comment by mohuishou** [comment]
感谢你的反馈，这个问题先关闭了哦
