### ISSUE TITLE
[我要回到风里了]: 课表显示日期不对

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#221]
我的“今日课表”显示的是昨天的课程

scuplus_version: 0.7.1
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 11.2 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，bug已经修复了但是要今天晚上或者明天才能发布新版本，版本审核需要时间

**Comment by mohuishou** [comment]
新版本已发布，如果发现没有更新，请后台退出小程序重新进入
