### ISSUE TITLE
[刘林虎]: 课表显示的时间是昨天的

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#222]
今天是星期二，但是课表显示的是星期一的

scuplus_version: 0.7.1
手机: Xiaomi-MIX 2-Android 8.0.0 
微信：6.6.5,SDK: 1.9.5

**Comment by mohuishou** [comment]
感谢你的反馈，bug已经修复了但是要今天晚上或者明天才能发布新版本，版本审核需要时间

**Comment by mohuishou** [comment]
新版本已发布，如果发现没有更新，请后台退出小程序重新进入
