### ISSUE TITLE
[SL]: 课程表故障

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#223]
课程表显示的一直是前一天的课程，刷新也没什么用

scuplus_version: 0.7.1
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 10.3.3 
微信：6.6.6,SDK: 1.9.98

**Comment by mohuishou** [comment]
新版本已发布，如果发现没有更新，请后台退出小程序重新进入
