### ISSUE TITLE
[克斯维尔的明天]: 账号密码正确却无法绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#224]
如题

scuplus_version: 0.7.1
手机: vivo-vivo V3-Android 5.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请使用 my.scu.edu.cn 的账号密码而不是教务处的。可以到这个网站上修改重置密码。如果确认能登陆这个网站但是无法绑定的话，请加入用户QQ群反馈一下详细信息，欢迎加入We川大用户交流，群聊号码：698433701
