### ISSUE TITLE
[北念]: 课表

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#226]
课表周二显示周一课表

scuplus_version: 0.7.1
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 10.3.3 
微信：6.6.6,SDK: 1.9.98

**Comment by mohuishou** [comment]
感谢你的反馈，bug已经修复了但是要今天晚上或者明天才能发布新版本，版本审核需要时间

**Comment by mohuishou** [comment]
新版本已发布，如果发现没有更新，请后台退出小程序重新进入
