### ISSUE TITLE
[星星]: 可以解绑吗

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#228]
请问一下之前查看成绩，绑定了别人的，账号就无法解绑了吗?

scuplus_version: 0.7.3
手机: HUAWEI-HUAWEI CAZ-AL10-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
可以更换绑定账号，在个人中心

**Comment by mohuishou** [comment]
暂时还不支持直接接触绑定，这个要后期再做
