### ISSUE TITLE
[朱智慧]: 校园卡刷新没有用

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#229]
校园卡的余额和交易流水一直是第一天的，刷新和退出重进都没有用

scuplus_version: 0.7.3
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 11.3 
微信：6.6.6,SDK: 1.9.98

**Comment by mohuishou** [comment]
从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，如果下周还无法访问再考虑实现单独绑定机制
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
