### ISSUE TITLE
[6ev]: 建议

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#230]
课程表字体增大
好多其他地方，比如资讯标题，也需要增大字体
课程表增加添加课程功能
做成超表那样

scuplus_version: 0.7.3
手机: vivo-vivo X9s-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的建议，课表字体很小的主要原因是大了有些课程会显示不下，字体的我尽量在不影响布局的情况下进行调整优化
