### ISSUE TITLE
[Mega]: 空教室关键字

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#231]
空教室关键字中有个顿号，有点不走心了，哈哈(ಡωಡ)hiahiahia

scuplus_version: 0.7.3
手机: Xiaomi-MI 6-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by scuplus** [comment]
哈😄    $$$Mega

**Comment by mohuishou** [comment]
感谢你的反馈，问题关闭了哦
