### ISSUE TITLE
[顾昀]: 校历改良

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#232]
可以在校历上标注节假日与第几周

scuplus_version: 0.7.3
手机: HUAWEI-MHA-AL00-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
第几周已经有了，节假日考虑后期再做，目前还是实现功能为主

**Comment by mohuishou** [comment]
感谢你的反馈
