### ISSUE TITLE
[Manners]: 请问一下

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#242]
大一新生登不上是什么原因呀

scuplus_version: 0.7.4
手机: Meizu-M5 Note-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
大一的同学可以用的，如果无法登录应该是这个问题: 如果反馈账号密码错误请使用 my.scu.edu.cn 的账号密码而不是教务处的。可以到这个网站上修改重置密码

**Comment by scuplus** [comment]
应该是学院的问题 物院还没加进去 学长加油哈！！！ 微信小程序比赛祝夺冠！！   $$$Manners

**Comment by mohuishou** [comment]
你可以尝试能不能登录这个网站my.scu.edu.cn，只要这个可以登录应该就可以，谢谢祝福，能过筛选就不错了0.0

**Comment by scuplus** [comment]
登不进去 学长可以去看看什么问题 我觉得能用的话可以去推一波 真的很棒了！！   $$$Manners

**Comment by mohuishou** [comment]
加一下群，看看吧，用户交流、反馈群: 698433701，我是群主
