### ISSUE TITLE
[水心]: 登不进

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#244]
没有我的用户名

scuplus_version: 0.7.4
手机: OPPO-OPPO R9tm-Android 5.1 
微信：6.6.6,SDK: 1.9.97

**Comment by mohuishou** [comment]
账号密码错误请使用 my.scu.edu.cn 的账号密码而不是教务处的。可以到这个网站上修改重置密码，过段时间会把账号绑定换到教务处，敬请期待

**Comment by mohuishou** [comment]
不用谢，问题关闭了哦
