### ISSUE TITLE
[Totoro]: 一卡通消息是4.4的，现在是4.15

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#245]
一卡通消息是4.4的，现在是4.15

scuplus_version: 0.7.4
手机: Meizu-m3 note-Android 5.1 
微信：6.6.1,SDK: 1.9.9

**Comment by mohuishou** [comment]
从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，正在考虑实现单独绑定机制
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
