### ISSUE TITLE
[马不二]: 一卡通

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#248]
一卡通的实时信息无法刷新出来
谢谢你们

scuplus_version: 0.7.4
手机: vivo-vivo X7-Android 5.1.1 
微信：6.6.6,SDK: 2.0.1

**Comment by mohuishou** [comment]
从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，正在考虑实现单独绑定机制，感谢你的反馈
