### ISSUE TITLE
[zero]: 一卡通功能无法使用

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#250]
查询不到一卡通的数据

scuplus_version: 0.7.4
手机: OPPO-OPPO R11-Android 7.1.1 
微信：6.6.6,SDK: 2.0.1

**Comment by mohuishou** [comment]
从4.5开始暂时无法通过 my.scu.edu.cn访问到一卡通服务，目前暂时先等待一段时间，正在考虑实现单独绑定机制
感谢你的反馈，可以添加用户交流、反馈QQ群: 698433701
