### ISSUE TITLE
[SL]: 下方小模块的放置位置

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#251]
可以调整下面那些缩略模块的放置位置吗，就比如可以让考表放在借阅书籍前之类的，谢谢

scuplus_version: 0.7.4
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 10.3.3 
微信：6.6.6,SDK: 2.0.1

**Comment by mohuishou** [comment]
感谢你的反馈，这个在小程序当中实现还有难点，后期会实现的
