### ISSUE TITLE
[Alexander]: 课表

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#252]
课表查询不了

scuplus_version: 0.7.4
手机: Sony-G8342-Android 8.0.0 
微信：6.6.2,SDK: 1.9.97

**Comment by mohuishou** [comment]
请问下拉刷新反馈什么信息呢

**Comment by scuplus** [comment]
我没有下拉当时课表没问题啦。😅😅   $$$Alexander
