### ISSUE TITLE
[云销雨霁]: 11

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#253]
哈哈哈

scuplus_version: 0.7.4
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 11.1.2 
微信：6.6.5,SDK: 1.9.97

**Comment by scuplus** [comment]
GG   $$$云销雨霁

**Comment by mohuishou** [comment]
请不要反馈无关内容哦，问题关闭了
