### ISSUE TITLE
[wwh]: 大写X结尾认证问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#257]
绑定不上

scuplus_version: 0.7.4
手机: Xiaomi-MI 5-Android 7.0 
微信：6.6.6,SDK: 2.0.1

**Comment by mohuishou** [comment]
如果反馈账号密码错误请使用 my.scu.edu.cn 的账号密码而不是教务处的。可以到这个网站上修改重置密码,如果结尾需要用小写x,如果还是不行到这个网站重置一下密码
