### ISSUE TITLE
本地如何运行

### ISSUE THREAD

**Issue by Ex-Caliburn** [mohuishou/scuplus-wechat#258]
本地npm run dev 如何正常运行，需要把本地全改成 wyp后缀嘛

**Comment by mohuishou** [comment]
不需要，npm install之后运行就可以了

**Comment by Ex-Caliburn** [comment]
误VM2234:2 未找到 app.json 中的定义的 pages "pages/my/feedback" 对应的 JS 文件

**Comment by Ex-Caliburn** [comment]
明明有，但是会报错

**Comment by mohuishou** [comment]
额,不是用 `npm run dev`运行,请先`npm install wepy-cli -g` ,然后用 `wepy build -w`

**Comment by Ex-Caliburn** [comment]
我是这么做的还是不行

**Comment by mohuishou** [comment]
看一下console的错误信息

**Comment by Ex-Caliburn** [comment]
VM1049:2 未找到 app.json 中的定义的 pages "pages/my/feedback" 对应的 JS 文件
(anonymous) @ VM1049:2 还是那个错误。，

**Comment by mohuishou** [comment]
是运行wepy的终端log，这种错误就表示文件编译失败了

**Comment by ttfather** [comment]
我也遇到了同样的错误

**Comment by ttfather** [comment]
编译的时候报错了
![wechuanda](https://user-images.githubusercontent.com/20608641/39339484-a6183c6c-49fb-11e8-9e97-7dfe73fcf5c8.png)

**Comment by mohuishou** [comment]
https://github.com/mohuishou/scuplus-wechat/issues/261 
看一下这个应该是一个问题

**Comment by mohuishou** [comment]
@ttfather 上面那个问题的解决方法不行？

**Comment by kejianlin** [comment]
我也是出现同样的报错，请问你们解决了吗？
