### ISSUE TITLE
课程表bug

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#26]
课程名比较长的时候课程表会错乱
有的课程只有教室没有课程名

scuplus_version: 0.5.0
手机: Xiaomi-Mi Note 3-Android 7.1.1 
微信：6.6.3,SDK: 1.9.91

**Comment by mohuishou** [comment]
https://github.com/mohuishou/scuplus-wechat/commit/52855effadff246758d7d27c9e37e18f02691521
