### ISSUE TITLE
[Frederick Wang]: 无法获取课程表、成绩

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#260]
无法获取课程表和成绩…很悲伤

scuplus_version: 0.7.4
手机: Xiaomi-Mi Note 3-Android 7.1.1 
微信：6.6.6,SDK: 2.0.1

**Comment by mohuishou** [comment]
下拉刷新试试呢，如果还是没有请加用户群反馈一下详细信息谢谢
