### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by DGZing** [mohuishou/scuplus-wechat#261]
你好，请问我在本地编译出现这种错误怎么解决
![image](https://user-images.githubusercontent.com/38136018/39091027-779c4ecc-461e-11e8-91a3-037f4fb1f149.png)

**Comment by mohuishou** [comment]
这是微信小程序，不是小游戏

**Comment by DGZing** [comment]
抱歉  导入项目时误选择了这一项导致默认为小游戏了
![image](https://user-images.githubusercontent.com/38136018/39091270-50804668-4623-11e8-9cb6-93eff6e1c687.png)
重新选择小程序导入后出现了下面这个错误
![image](https://user-images.githubusercontent.com/38136018/39091276-805e2620-4623-11e8-9f2e-9d8393fa06a0.png)

**Comment by mohuishou** [comment]
命令行中运行wepy build -w看看有什么报错

**Comment by mohuishou** [comment]
这个错误应该是编译失败了

**Comment by DGZing** [comment]
我将命令行中的信息输出到文件中，里面有一些错误
[1.txt](https://github.com/mohuishou/scuplus-wechat/files/1935202/1.txt)
在命令行中提示的是
![image](https://user-images.githubusercontent.com/38136018/39091409-fd597736-4625-11e8-81a5-94cca2db58ad.png)

**Comment by mohuishou** [comment]
哦哦,我config相关文件没有在版本里面, config文件夹当中新建`index.js`文件
```javascript
const env = process.env.NODE_ENV === 'production' ? 'prod' : 'dev'
const domains = {
  dev: 'https://xxxx.cn',
  prod: 'https://xxxx.cn'
}
export const domain = domains[env]
export const version = '0.8.0'
```

**Comment by DGZing** [comment]
感谢您的指导 这个问题解决了
但是还存在上面1.txt中的编译错误问题
在微信开发者工具的控制台中提示的是这种错误
![tim 20180422134014](https://user-images.githubusercontent.com/38136018/39091954-b719140e-4632-11e8-89e3-753acbc95ab7.png)

**Comment by mohuishou** [comment]
微信开发者工具需要关闭es6转es5,代码压缩等选项

**Comment by DGZing** [comment]
这是现在的设置 还会提示那些错误
![image](https://user-images.githubusercontent.com/38136018/39092014-12a9fa0c-4635-11e8-968a-f1cdb08537ed.png)

**Comment by DGZing** [comment]
更改设置后再重新编译就好了 非常感谢您的解答
请问在没有绑定账号的情况下是否可以预览那些功能

**Comment by mohuishou** [comment]
暂时不能,你想要直接预览的话,只有自己修改代码逻辑了

**Comment by DGZing** [comment]
好的 明白了 非常感谢您的耐心解答

**Comment by DGZing** [comment]
好的 明白了 非常感谢您的耐心解答

**Comment by mohuishou** [comment]
没事，问题关闭了
