### ISSUE TITLE
[斯温]: 讲座信息汇总

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#263]
建议标签设置中加设“学术讲座”，以汇总川大各网站以及各学院通知的讲座信息，谢谢～

scuplus_version: 0.7.4
手机: Xiaomi-MI 5-Android 7.0 
微信：6.6.6,SDK: 2.0.2

**Comment by mohuishou** [comment]
感谢你的建议，这个之后可以加上
