### ISSUE TITLE
[哈哈哈是我啦]: 资讯页面惊现代码？

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#264]
😥

scuplus_version: 0.7.4
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.3 
微信：6.6.6,SDK: 2.0.2

**Comment by mohuishou** [comment]
应该是教务处的一些新闻吧，这个问题还在看怎么解决，转码出了一点问题
