### ISSUE TITLE
首页数据刷新不及时

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#27]
在课程表界面或者是图书借阅界面更新了数据，返回首页，首页卡片数据没有刷新

scuplus_version: 0.5.0
手机: Xiaomi-Mi Note 3-Android 7.1.1 
微信：6.6.3,SDK: 1.9.91

**Comment by mohuishou** [comment]
https://github.com/mohuishou/scuplus-wechat/commit/52855effadff246758d7d27c9e37e18f02691521
