### ISSUE TITLE
[9527]: 课程表

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#277]
希望课程表加强上课时间的信息，第几周上到第几周，反正课程表的格子挺大的，为什么不多放一点信息呢

scuplus_version: 0.7.4
手机: HONOR-STF-AL10-Android 8.0.0 
微信：6.6.6,SDK: 2.0.2

**Comment by mohuishou** [comment]
这个暂时不会添加，下一个版本课程相关会有一个大的更新，到时候点击相关课程就可以看到该课程详细的信息了，感谢你的反馈
