### ISSUE TITLE
[Echo]: 无法登录

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#280]
登录的学号是对的，密码也按照下面的提示了，但是它说无此账号或者密码错误。

scuplus_version: 0.8.1
手机: vivo-vivo X9Plus L-Android 7.1.2 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
请尝试使用浏览器访问my.scu.edu.cn这个网站呢
