### ISSUE TITLE
[李鬼]: 建议课程评价改为匿名

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#282]
如题

scuplus_version: 0.8.1
手机: iPhone-iPhone SE<iPhone8,4>-iOS 11.3 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
感谢你的反馈，匿名功能暂时不会添加，目前所获取的只是微信昵称并不是真实姓名，所以并没有那么直接

**Comment by scuplus** [comment]
感觉微信头像和昵称晾在那里好不舒服呀，想删评论又删不掉 ，同一节课的又都是认识的人，一眼都看到是谁了   $$$李鬼
