### ISSUE TITLE
[°恶魔先森つ]: 校园卡余额

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#283]
余额查询功能不能更新了

scuplus_version: 0.8.1
手机: vivo-vivo X6L-Android 5.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，不知道这个更新指的是怎么样的更新方式？一卡通界面会在后期重构优化，不过目前还是以功能实现为主

**Comment by scuplus** [comment]
就是我的余额显示和消费记录还是三月份的   刷新也没用   $$$°恶魔先森つ

**Comment by mohuishou** [comment]
刚刚检查了一下，学校一卡通查询服务突然不能访问了，这个暂时无解，在五一之前其实都还是可以访问的
