### ISSUE TITLE
[S.C.]: 无法绑定帐号

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#284]
绑定帐号时 显示用户不存在或密码错误
登录那个网页也登录不了

scuplus_version: 0.8.1
手机: HUAWEI-HUAWEI CAZ-AL10-Android 7.0 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
额，we川大目前绑定的账号是my.scu.edu.cn的账号，we川大只做绑定，没有办法修改账号密码等信息，具体信息需要在这个网站修改，后期会考虑更换主绑定账号为教务处账号，但是迁移还需要时间
