### ISSUE TITLE
[瓦蓝瓦蓝啊]: 为何还是登不上去0.0

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#285]
输入学号还是显示不存在或密码错误

scuplus_version: 0.8.1
手机: iPhone-iPhone 6<iPhone7,2>-iOS 10.3.3 
微信：6.6.1,SDK: 1.9.9

**Comment by mohuishou** [comment]
请问能登录my.scu.edu.cn这个网站么，能登陆这个网站应该就能绑定
