### ISSUE TITLE
[Missing In Action]: 考试提示存在bug

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#286]
第二天早上的考试，在第一天下午就提示今日要考试了。

scuplus_version: 0.8.1
手机: Xiaomi-MI 6-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，这的确是一个bug，之后会修复的

**Comment by mohuishou** [comment]
已修改，待发布
