### ISSUE TITLE
[Eylar]: 考试时间和教务处显示的不一样

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#287]
考试时间和教务处显示的不一样

scuplus_version: 0.8.1
手机: OPPO-R7Plusm-Android 5.1.1 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
请添加用户群反馈一下详细的截图吧，698433701

**Comment by scuplus** [comment]
嗯   $$$Eylar
