### ISSUE TITLE
[...]: 账号绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#288]
不能绑定账号，显示无此账号

scuplus_version: 0.8.1
手机: OPPO-OPPO R11-Android 7.1.1 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
下一个版本会更换主绑定账号为教务处账号，请耐心等待谢谢

**Comment by mohuishou** [comment]
已更新，现在可以使用教务处账号绑定了
