### ISSUE TITLE
[　　　　　　　　蜀人周建发]: 一卡通

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#291]
要是个人一卡通能对校类消费，分别对每个食堂，或者其他的店铺进行统计，生产个人统计图和账单（周，月，或者年），就觉得很棒。

scuplus_version: 0.8.1
手机: Xiaomi-Redmi Note 4-Android 6.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
这个提议很棒，但是目前暂时实现功能为主，这个功能放在长远规划里面了
