### ISSUE TITLE
无法获取考表信息

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#294]
更新后无法获取考表信息

scuplus_version: 0.8.1
手机: 360-1607-A01-Android 7.1.1 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
请先确认教务处有相关的考试信息，很有可能考试完之后教务处考试信息会关闭

**Comment by scuplus** [comment]
不，还没考完，19号还有一门军理没考。更新前是有显示的。

**Comment by mohuishou** [comment]
你看一下教务处里面有没有呢？

**Comment by mohuishou** [comment]
还有，反馈一下你的学号吧

**Comment by scuplus** [comment]
有

**Comment by scuplus** [comment]
2017141472035

**Comment by mohuishou** [comment]
数据库里面是有你的考试信息的，添加一下用户群私聊一下群主吧，谢谢698433701
