### ISSUE TITLE
课程平均分功能似乎有一些问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#297]
感觉有些课平均分不准啊 

scuplus_version: 0.8.1
手机: iPhone-iPhone 6<iPhone7,2>-iOS 10.3.2 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
这个只能统计到we川大绑定用户的平均分，所有需要大家宣传一下，使用的人越多，统计越准确，这个没有办法

**Comment by scuplus** [comment]
原来如此！谢谢！会帮宣传一下的～

**Comment by mohuishou** [comment]
感谢，这个问题关闭了哦
