### ISSUE TITLE
密码

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#299]
我身份证最后一位是X，密码就怎么都不对

scuplus_version: 0.8.1
手机: vivo-vivo Y66i-Android 7.1.2 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
请问你绑定的什么账号呢

**Comment by scuplus** [comment]
行了，试了很多次，终于进去了

**Comment by mohuishou** [comment]
没有问题就好，这个issue关闭了
