### ISSUE TITLE
一卡通流水

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#301]
每次刷新的时候会多出现一次 
比如刷新n次会出现n行相等内容
可能是爬了数据没清楚直接覆盖了

scuplus_version: 0.8.1
手机: iPhone-iPhone 8 Plus (GSM+CDMA)<iPhone10,2>-iOS 11.2.6 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
这个其实是故意的，不然有一些数据会覆盖不到
