### ISSUE TITLE
图书搜索

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#305]
图书搜索为什么显示搜不到啊

scuplus_version: 0.9.1
手机: vivo-vivo X6SPlus D-Android 5.1.1 
微信：6.6.6,SDK: 2.0.4

**Comment by mohuishou** [comment]
重新试试或者换个关键词呢，一般应该是没有问题的，目前有个bug会导致有一定的几率需要重试，这个后面会改

**Comment by scuplus** [comment]
emmm我搜的会计这个关键词

**Comment by mohuishou** [comment]
是有结果的，对了不要点搜索，点空白的地方

**Comment by scuplus** [comment]
啊好的晓得了

**Comment by mohuishou** [comment]
这个问题先关闭了，这个bug已经修复了，今天晚点会发布新版
