### ISSUE TITLE
建议把报修加进去

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#310]
~

scuplus_version: 0.9.2
手机: samsung-SM-A5009-Android 6.0.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
后勤部门的报修么？

**Comment by scuplus** [comment]
嗯嗯，

**Comment by mohuishou** [comment]
感谢你的反馈，这个添加到长远规划了
