### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#314]
身份证后有X使用无法登录

scuplus_version: 0.9.2
手机: HUAWEI-HWI-AL00-Android 8.0.0 
微信：6.6.6,SDK: 2.0.5

**Comment by mohuishou** [comment]
请问具体是什么账号，这个和X没有关系，如果是教务处如果能登录教务处就能绑定，如果是统一认证中心，请访问my.scu.edu.cn确保能够登录这个网站，能登录应该就能绑定

**Comment by scuplus** [comment]
可以在教务处登录  但是无法在认证中心登录
不知道怎么回事

**Comment by mohuishou** [comment]
密码不是同一个密码哦，统一认证中心上面的网站有一个忘记密码可以试试，然后也有一个使用说明可以看看，就在那个网站上
