### ISSUE TITLE
投诉

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#319]
您好，我昨天登陆了账号密码，今天就有人盗用我的校园网账号，看你们是开发阶段给你们提供了一个账号供你们试验debug，你们就是这样对待的，我保证，我的朋友，所有我认识的人，我保证宣传到底，不会让他们使用你们飞扬的任何产品，谢谢。

scuplus_version: 0.9.2
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.2.6 
微信：6.6.6,SDK: 2.0.5

**Comment by mohuishou** [comment]
同学有话好好说，请不要随意污蔑好么。。。我人都不在学校，用你的校园网账号干啥。。

**Comment by scuplus** [comment]
那我哪知道。。我从来都没背盗过账号。。登了系统之后就两天就被盗了。。我也很绝望啊_(:з」∠)_

**Comment by scuplus** [comment]
刚才真的着急态度不太好...但是...开发团队就你一个人吗233你没用不代表别人没用啊...而且我本来就很怀疑账号的安全性...我刚登完就出来这个事情...这让我咋放心/捂脸，再次道歉不该这么对你说话对不起qwq

**Comment by mohuishou** [comment]
首先解释一下，这是一个个人开发的小程序，开发运营设计都只有一个人，除非你主动把密码给我，不然我都无法直接查看你的密码的，密码是经过加密保存的。

**Comment by mohuishou** [comment]
然后校园网的密码和绑定账号的密码是独立的，这两者没有关联，除非你的两个密码完全一样，当然出现这种情况就是你从来没有改过默认密码，默认密码是很容易被盗的，这种情况首先首先改密码，不过现在可能改不了了，你可以搜索四川大学校园网自助改密应该能搜到一个网址，在白天可以自助改密码

**Comment by scuplus** [comment]
嘤嘤嘤对不起qwq主要当时急着交材料登不上去就很气（虽然不该怪你嘤），我已经改完密码惹，就还是道歉不该对你这么说话qwq（你一定要原谅我！/叉腰）最后你的小程序hin棒棒啦我再把他装回来！/真诚脸

**Comment by mohuishou** [comment]
没事啦，还是要注意保护信息安全初始密码这种东西建议还是改掉，身份证后六位有很多种办法可以获取到

**Comment by scuplus** [comment]
嘤嘤嘤/对手指！懒惰少女就一直懒着没用改qwq蟹蟹小姐姐/女装小哥哥！/斜眼笑

**Comment by mohuishou** [comment]
这个问题关闭了哦，解决了就好
