### ISSUE TITLE
总是显示账号不存在

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#323]
明明正确且存在，但就是登不进去

scuplus_version: 0.9.2
手机: OPPO-OPPO R7s-Android 4.4.4 
微信：6.6.6,SDK: 2.0.5

**Comment by mohuishou** [comment]
应该是统一认证中心吧，统一认证中心请访问my.scu.edu.cn有一个忘记密码可以试试，然后也有一个使用说明可以看看，就在那个网站上
