### ISSUE TITLE
麻烦看下邮箱，我发您了，可以沟通下

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#331]
麻烦看下邮箱，我发您了，可以沟通下

scuplus_version: 0.9.2
手机: HUAWEI-EVA-AL00-Android 7.0 
微信：6.6.6,SDK: 2.0.6

**Comment by mohuishou** [comment]
看到了，感谢你的邀请，暂时没有找工作的打算

**Comment by scuplus** [comment]
呃，好的。希望以后有机会合作。我们是北京亿佰教育科技有限公司

**Comment by mohuishou** [comment]
好的，谢谢
