### ISSUE TITLE
教务处密码

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#339]
统一一下密码，密码太多记不住。

scuplus_version: 0.9.2
手机: HUAWEI-HWI-AL00-Android 8.0.0 
微信：6.6.6,SDK: 1.9.91

**Comment by mohuishou** [comment]
这个锅要学校背，最开始使用统一认证中心，但是统一认证中心的账号有的同学没有，而且有很多问题，所以就只能每个系统单独绑定了，当时不建议把所有系统密码弄成一样的，绑定到we川大之后就不用记这么多了
