### ISSUE TITLE
学校各部门联系或反馈方式板块

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#345]
有些时候需要联系学校某些部门或者组织，或办事或反馈，但是比较难找到联系方式。
1.比如，教学楼饮水器等物损坏，该找谁，该怎么联系。
2.比如，校园110快速联系电话等。
3.增加各学校部门组织办事指南。
4.体质测试系统链接。
5.开放式师生论坛。

scuplus_version: 0.9.2
手机: samsung-SM-G9300-Android 7.0 
微信：6.6.6,SDK: 2.0.7

**Comment by mohuishou** [comment]
感谢你的建议，联系方式已经在下个版本规划了，体测的话后期再考虑，论坛相关已经有规划了
