### ISSUE TITLE
账号密码错误或不存在

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#349]
统一中心绑定总是显示账号不存在或密码错误，但是教务处绑定可以完成

scuplus_version: 0.9.2
手机: iPhone-iPhone 8 Plus (GSM+CDMA)<iPhone10,2>-iOS 11.0.3 
微信：6.6.6,SDK: 2.0.7

**Comment by mohuishou** [comment]
统一认证中心请访问my.scu.edu.cn有一个忘记密码可以试试，然后也有一个使用说明可以看看，就在那个网站上
