### ISSUE TITLE
校园卡流水账

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#352]
更新失败了。。

scuplus_version: 0.9.2
手机: HONOR-PLK-TL01H-Android 6.0 
微信：6.6.6,SDK: 2.0.8

**Comment by mohuishou** [comment]
学校的统一认证中心无法访问了，需要等学校的系统恢复

**Comment by mohuishou** [comment]
已经可以了下拉刷新就行了
