### ISSUE TITLE
一卡通信息已经不更新了

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#353]
截止5月10日一卡通信息已经不更新了

scuplus_version: 0.9.2
手机: Xiaomi-MI 5-Android 7.0 
微信：6.6.6,SDK: 2.0.8

**Comment by mohuishou** [comment]
学校的一卡通web系统最近访问有问题，所以更新不了

**Comment by mohuishou** [comment]
已经可以了下拉刷新就行了
