### ISSUE TITLE
学号登不进去

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#356]
竟然不能绑定，一次也就算了，换了时间也不行，那个密码教务处都能进去，这边就怎么进不去了，

scuplus_version: 0.9.2
手机: OPPO-OPPO A79k-Android 7.1.1 
微信：6.6.6,SDK: 2.0.8

**Comment by mohuishou** [comment]
统一认证中心的密码和教务处密码是独立的，如果不知道请访问my.scu.edu.cn找回
