### ISSUE TITLE
寻课用不了嘤嘤嘤

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#357]
寻课用不了嘤嘤嘤

scuplus_version: 0.9.2
手机: OnePlus-ONEPLUS A5010-Android 8.0.0 
微信：6.6.6,SDK: 2.0.8

**Comment by mohuishou** [comment]
可以用的啊？具体怎么用不了了？

**Comment by scuplus** [comment]
说我没绑定。。我绑了教务处和图书馆，另外一个统一身份认证绑不了

**Comment by mohuishou** [comment]
寻课目前的确是需要绑定统一认证账号，下一个版本会修改成教务处账号，统一认证中心的密码和教务处密码是独立的，如果不知道请访问my.scu.edu.cn找回

**Comment by scuplus** [comment]
但是我不知道统一认证的账号。。

**Comment by mohuishou** [comment]
账号是学号密码默认身份证后六位，如果不知道可以到上面那个网址找回，也有一个说明文档可以看看
