### ISSUE TITLE
一卡通信息更新延迟

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#358]
目前，只能查到10天前一卡通消费记录，建议一卡通消费记录可以查询到前一天消费记录，

scuplus_version: 0.9.2
手机: HONOR-PRA-AL00X-Android 7.0 
微信：6.6.6,SDK: 2.0.8

**Comment by mohuishou** [comment]
学校的一卡通web系统访问不了了，时不时的会有问题，一般要等个几天就会好
