### ISSUE TITLE
资讯里添加研究生院的信息

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#36]
你好，请问能不能在资讯栏里添加研究生院的信息啊？

scuplus_version: 0.5.0
手机: xiaomi-Redmi Note 4X-Android 7.0 
微信：6.6.3,SDK: 1.9.91

**Comment by mohuishou** [comment]
0.7.0会对资讯页面重构，可以做

**Comment by mohuishou** [comment]
新版本已添加
