### ISSUE TITLE
寻课搜索板块不显示结果

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#362]
查找具体课程或考试时，提示成功但不显示内容

scuplus_version: 0.9.2
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.2.5 
微信：6.6.6,SDK: 2.0.8

**Comment by mohuishou** [comment]
这个是因为，没有搜索到结果，要输入正确的课程名可以模糊适配的，技术高数的课程名其实叫微积分，搜高数没用，微积分就行了

**Comment by scuplus** [comment]
输入部分正确的课程名也没有模糊匹配成功

**Comment by mohuishou** [comment]
请问具体关键词是什么呢，我试过微积分是可以的
