### ISSUE TITLE
首页banner图

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#38]
首页banner图大于2个时，后面的图不显示

scuplus_version: 0.5.0
手机: devtools-iPhone 6-iOS 10.0.1 
微信：6.5.6,SDK: 1.6.4

**Comment by mohuishou** [comment]
https://github.com/mohuishou/scuplus-wechat/commit/863e769ba48d4d9b4cbbf5237fe345190c328737
