### ISSUE TITLE
标题不能为空

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#382]
补过卡就没有流水查看了…

scuplus_version: 0.9.2
手机: iPhone-iPhone 8 Plus (GSM+CDMA)<iPhone10,2>-iOS 11.3.1 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
学校的一卡通web系统访问不了了，时不时的会有问题，一般要等个几天就会好
