### ISSUE TITLE
为什么我没有收到公众号的消息通知呢，比如成绩更新之类的😂 

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#384]
为什么我没有收到公众号的消息通知呢，比如成绩更新之类的😂 

scuplus_version: 0.9.2
手机: nubia-NX563J-Android 7.1.1 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
通知服务只有在最近七天内使用过的同学才有可能触发，这个是微信的规则，然后就是系统有自动更新到你的成绩有变更之类的才会发送

**Comment by scuplus** [comment]
哇感恩！！！这个小程序太好用了

**Comment by mohuishou** [comment]
Thanks♪(･ω･)ﾉ，觉得可以就帮忙安利一下吧

**Comment by scuplus** [comment]
安利安利！(人 •͈ᴗ•͈)۶♡♡比心心

**Comment by mohuishou** [comment]
Thanks♪(･ω･)ﾉ
