### ISSUE TITLE
一卡通余额问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#385]
显示的一卡通余额和实际余额不一致，六月份消费过可是只显示到5月17号

scuplus_version: 0.9.2
手机: iPhone-iPhone 8 (GSM+CDMA)<iPhone10,1>-iOS 11.3 
微信：6.6.6,SDK: 2.0.9

**Comment by scuplus** [comment]
好的，辛苦了

**Comment by mohuishou** [comment]
感谢你的理解，谢谢反馈
