### ISSUE TITLE
一卡通补办后没有消费数据

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#390]
一卡通消费数据刷新后也只是前一张卡的消费数据，补办后的那张卡一直刷新不出消费数据

scuplus_version: 0.9.2
手机: HONOR-BLN-AL20-Android 7.0 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
这个不是补办的锅，最近学校一卡通的网站访问不了了，只有等学校这边看能不能恢复

**Comment by mohuishou** [comment]
这个不是补办的锅，最近学校一卡通的网站访问不了了，只有等学校这边看能不能恢复

**Comment by scuplus** [comment]
好的，谢谢啦

**Comment by mohuishou** [comment]
感谢您的反馈，觉得不错就帮忙安利一下哦
