### ISSUE TITLE
课程平均分

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#392]
为啥看不了课程均分了……换课感觉很有用呀！求指点

scuplus_version: 0.9.2
手机: Xiaomi-MIX 2-Android 8.0.0 
微信：6.6.6,SDK: 2.0.9

**Comment by mohuishou** [comment]
暂时下架了，因为由于平均分计算是计算的we川大用户的平均分，准确度不高，为了不造成误解先暂时下架了，等用户量上来了再考虑重新上线吧
