### ISSUE TITLE
添加活动报名功能的建议

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#394]
在大学生活中，学生活动是一大部分，学生会，俱乐部，各种活动的报名工作如火如荼。在过去，需要组织者不断确认报名人信息，发送短信等大量工作，对于同学而言，报名的活动时间也不方便整理在一起。希望we川大能发布这项功能，组织者发起一个活动，同学们申请，并在小程序中确认报名信息等

scuplus_version: 0.9.2
手机: iPhone-iPhone 7 Plus<iPhone9,2>-iOS 11.3 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
感谢您的建议，这是一个很棒的idea，但是这个功能相对来说比较复杂，后面有时间的话考虑加上
