### ISSUE TITLE
不显示平均分

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#395]
为什么之前都可以显示课程平均分今天看不到

scuplus_version: 0.9.2
手机: HUAWEI-VTR-AL00-Android 7.0 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
暂时下架了，因为由于平均分计算是计算的we川大用户的平均分，准确度不高，为了不造成误解先暂时下架了，等用户量上来了再考虑重新上线吧
