### ISSUE TITLE
成绩计算

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#396]
绩点的计算对吗？是最新的计算方式吗？

scuplus_version: 0.9.2
手机: HONOR-BKL-AL20-Android 8.0.0 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
只能说是按照最新的计算的，具体的计算规则可以在we川大->成绩->帮助中查看，最后结果仅供参考，因为有的学院的具体一些细节的处理不一样，但是差距应该不会很大
