### ISSUE TITLE
本周王力宏演唱会求望江或华西同行的小伙伴

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#397]
我们有两人，在望江校区，求能够一起约车的小伙伴同行

scuplus_version: 0.9.2
手机: honor-FRD-AL00-Android 7.0 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
😂😂😂这是反馈，不是聊天室哦，类似社交功能下个大版本会上线

**Comment by scuplus** [comment]
抱歉，是我发错了

**Comment by mohuishou** [comment]
没事的，下个大版本就会上线类似微博的社交功能了，尽请期待
