### ISSUE TITLE
评教是不是出问题了…

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#398]
我的评教进去之后是空白  只有 四川大学快捷评教 几个字  没有拉取到列表  emmmm不让提交图片

scuplus_version: 0.9.2
手机: Xiaomi-MIX 2-Android 8.0.0 
微信：6.6.6,SDK: 2.0.9

**Comment by mohuishou** [comment]
重新试试呢，我刚刚试了是有结果的
