### ISSUE TITLE
一卡通余额以及课表

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#40]
一卡通余额流水有重复显示的现象，还出现一刷新余额改变的现象。

建议本周不上的课程不提醒或者直接不显示。

scuplus_version: 0.5.0
手机: HONOR-KNT-AL10-Android 7.0 
微信：6.6.3,SDK: 1.9.91

**Comment by mohuishou** [comment]
一卡通问题已修复，docker时区问题

**Comment by mohuishou** [comment]
本周课程问题加入下一版本开发计划
