### ISSUE TITLE
课表和学年不对应，切换不回去

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#400]
重新登陆后，显示的是大四的课程表，但现在大三课都没上完，没法切换回去

scuplus_version: 0.9.2
手机: HUAWEI-VKY-AL00-Android 8.0.0 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
😂😂这是一个设计失误的地方，课程表没有学年设置，手动更新之后，会直接覆盖，暂时没有办法恢复，后面的版本更新会添加学期设置

**Comment by mohuishou** [comment]
已添加学期设置
