### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#402]
功能太强大啦，联系可以合并川大生活服务app里的充值缴费之类的功能！！！祝we越来越好~~

scuplus_version: 0.9.2
手机: iPhone-iPhone 7 Plus<iPhone9,2>-iOS 11.4 
微信：6.6.7,SDK: 2.0.9

**Comment by mohuishou** [comment]
感谢你的反馈，充值缴费目前来看是没有办法的了，毕竟是个人开发的小程序。不过会继续添加更多好用的功能的，新版本优化新增的许多功能，尽请期待
