### ISSUE TITLE
课程表，课程搜索

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#404]
课程表建议左滑右滑切换周数
课程搜索建议输入课程名或老师名，很多课程如微积分，老师太多，想具体找某个老师很麻烦，搜老师名就比较容易
加油

scuplus_version: 0.11.0
手机: OPPO-OPPO R11st-Android 7.1.1 
微信：6.6.6,SDK: 2.0.9

**Comment by mohuishou** [comment]
感谢你的建议

**Comment by mohuishou** [comment]
课程搜素已更新
