### ISSUE TITLE
绑定一卡通显示密码输入错误或账号不存在

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#408]
账号密码绝对没错

scuplus_version: 0.11.0
手机: HUAWEI-LON-AL00-Android 8.0.0 
微信：6.6.7,SDK: 2.1.0

**Comment by mohuishou** [comment]
请确认能登录my.scu.edu.cn，这个密码不是一卡通的密码，也不是教务处的密码，如果可以登录上述网站，但是无法绑定，添加用户群联系一下群主解决，谢谢
