### ISSUE TITLE
关于校历

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#409]
校历里面的假期希望可以标注一下，比如在下面加个点或者颜色变一下。现在的这个看不出法定节日的假期在哪几天

scuplus_version: 0.11.0
手机: Xiaomi-MI MAX 2-Android 7.1.1 
微信：6.6.7,SDK: 2.1.0

**Comment by mohuishou** [comment]
感谢你的建议，这个后期会实现的
