### ISSUE TITLE
您好！

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#41]
您好 请问您是川大的学长吗？我是软件学院的学生 对您的作品很感兴趣 如果可以的话能否在技术方面向您讨教一番呢 我的qq是1071329235 邮箱同. 

scuplus_version: 0.5.0
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.3 
微信：6.6.2,SDK: 1.9.91

**Comment by mohuishou** [comment]
已发送邮件
