### ISSUE TITLE
无成绩提醒推送

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#411]
原先的成绩提醒消失了，就是新出的几科成绩没有及时推送提醒，希望能恢复推送

scuplus_version: 0.11.0
手机: xiaomi-Redmi Note 5-Android 8.1.0 
微信：6.6.6,SDK: 2.0.9

**Comment by mohuishou** [comment]
感谢您的反馈，刚刚测试过了通知系统可以成功发送成绩通知。你没有收到通知可能是以下几种情况：
1. 七天内没有使用过小程序，只有使用过才有权限
2. 通知设置中关闭了通知
3. 系统后台还没有更新成绩，你先自己手动刷新了
4. 系统后台更新成绩失败，最近教务处访问压力较大有一定的可能性出现这个问题
