### ISSUE TITLE
周五下午和晚上的课表无法正常显示

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#412]
如题，没法插入图片...我周五下午和晚上的两门课都没显示，其他正常。

scuplus_version: 0.11.0
手机: Xiaomi-MI 6-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
添加一下用户群，私聊一下群主吧，698433701
