### ISSUE TITLE
绩点

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#413]
2017级，今天成绩的绩点突然变成了老版计算方式

scuplus_version: 0.11.3
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.4 
微信：6.7.0,SDK: 2.1.0

**Comment by mohuishou** [comment]
更新新版本出了点bug，下个版本解决，感谢你的反馈

**Comment by mohuishou** [comment]
已更新，请退出重进查看
