### ISSUE TITLE
绩点计算

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#414]
又变回以前的绩点计算方式了

scuplus_version: 0.11.3
手机: HONOR-DUK-AL20-Android 8.0.0 
微信：6.6.7,SDK: 2.1.0

**Comment by mohuishou** [comment]
更新的时候学期识别出了一点bug，已经提交新版本，等微信审核通过就可以修复这个问题，感谢反馈

**Comment by mohuishou** [comment]
已更新，请退出重进查看
