### ISSUE TITLE
绩点

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#417]
2018年上学期的绩点好像没有更新成新版

scuplus_version: 0.12.1
手机: OPPO-OPPO R11s Plus-Android 7.1.1 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
因为之前以为是2018年之后才生效，没想到上学期就生效了，这个下个版本再改一下

**Comment by mohuishou** [comment]
已修改
