### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#418]
增加食堂交流板块，对餐厅甚至细致到窗口菜品，有评价反馈，给大师傅们提供建议，给同学们提供交流平台，希望we川大越做越好

scuplus_version: 0.12.1
手机: OPPO-OPPO R9s-Android 6.0.1 
微信：6.6.7,SDK: 2.1.0

**Comment by mohuishou** [comment]
感谢你的建议，这个其实搜索一下川大后勤平台，有网页版的
