### ISSUE TITLE
或许可以有个留言板？

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#419]
大概就是标题这样，希望有个留言板可以发点消息之类的。

scuplus_version: 0.12.1
手机: HUAWEI-HUAWEI MLA-AL10-Android 7.0 
微信：6.6.7,SDK: 2.1.0

**Comment by mohuishou** [comment]
感谢你的反馈，如果有时间的话，下个版本会添加上类似的功能
