### ISSUE TITLE
考表时间不对

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#423]
期末考试毛概时间有错误

scuplus_version: 0.12.1
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 11.2.1 
微信：6.7.0,SDK: 2.1.0

**Comment by mohuishou** [comment]
添加一下qq群，698433701，联系一下群主，需要更详细的信息才行

**Comment by mohuishou** [comment]
下拉刷新应该就可以了，已修复
