### ISSUE TITLE
考表中考试时间错误

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#424]
毛概考试在教务系统中显示时间是为16:30-18:00，在小程序的考表中则显示为16:30-18:30。

scuplus_version: 0.12.1
手机: HUAWEI-EML-AL00-Android 8.1.0 
微信：6.6.7,SDK: 2.1.0

**Comment by mohuishou** [comment]
下拉刷新就可以了哦，才修复这个bug不久
