### ISSUE TITLE
培养方案

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#425]
可以增加个培养方案的查询，希望教务系统上有的功能这里都可以有。辛苦了

scuplus_version: 0.12.1
手机: OPPO-OPPO R9s-Android 6.0.1 
微信：6.6.7,SDK: 2.1.0

**Comment by mohuishou** [comment]
感谢你的建议，这个后面看有时间没有了，这个功能的使用频率不是很高
