### ISSUE TITLE
英文字母成绩绩点换算问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#426]
可爱的开发者，您好！绩点查询系统内，课程成绩为ABCD的换算绩点时为0，请您查看一下，谢谢您！辛苦了！

scuplus_version: 0.12.1
手机: iPhone-iPhone 6 Plus<iPhone7,1>-iOS 11.4 
微信：6.7.0,SDK: 2.1.0

**Comment by mohuishou** [comment]
感谢你的反馈，等会儿仔细看看

**Comment by mohuishou** [comment]
感谢你的反馈，已修复

**Comment by scuplus** [comment]
看到了，谢谢您，辛苦了！

**Comment by mohuishou** [comment]
这个问题关闭了哦，觉得不错就帮忙安利安利，谢谢了
