### ISSUE TITLE
成绩反馈

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#428]
换账号的时候 成绩不能迅速换过来 刷新好几次都不行

scuplus_version: 0.12.2
手机: iPhone-iPhone 7<iPhone9,1>-iOS 10.3.2 
微信：6.7.0,SDK: 2.1.2

**Comment by mohuishou** [comment]
😂😂怎么会有换账号需求，更换账号之后成绩需要手动下拉刷新才行哦
