### ISSUE TITLE
课程表反馈

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#429]
没办法及时跟着教务系统的课表更新 国际周选课看不到

scuplus_version: 0.12.2
手机: iPhone-iPhone 7<iPhone9,1>-iOS 10.3.2 
微信：6.7.0,SDK: 2.1.2

**Comment by mohuishou** [comment]
教务处上的本学期课表是否能看到呢，课程表需要手动下拉刷新哦
