### ISSUE TITLE
[　莫回首]: 资讯优化

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#43]
现在资讯信息更新很不及时，教务处的信息已经很久没更新过了

scuplus_version: 0.5.0
手机: devtools-iPhone 6-iOS 10.0.1 
微信：6.5.6,SDK: 1.6.4

**Comment by mohuishou** [comment]
0.7.0版本

**Comment by mohuishou** [comment]
test

**Comment by mohuishou** [comment]
新版本已更新
