### ISSUE TITLE
重复载入一门成绩

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#430]
读取成绩后，有一门选修重复出现两次。

scuplus_version: 0.12.2
手机: Xiaomi-MI 5s-Android 7.0 
微信：6.6.7,SDK: 2.1.2

**Comment by mohuishou** [comment]
已修复

**Comment by scuplus** [comment]
太强了！

**Comment by mohuishou** [comment]
觉得不错的话就帮忙安利一下哦，这个问题关闭了
