### ISSUE TITLE
无法绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#431]
在登陆my.scu.edu.cn后依旧无法绑定

scuplus_version: 0.12.2
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.3 
微信：6.7.0,SDK: 2.1.2

**Comment by mohuishou** [comment]
可以登录my.scu.edu.cn但是无法绑定we川大么？如果是这样加一下用户QQ群，联系一下群主吧
