### ISSUE TITLE
教务处推送建议

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#432]
希望可以增加教务处新闻的推送

scuplus_version: 0.12.4
手机: iPhone-iPhone SE<iPhone8,4>-iOS 12.0 
微信：6.7.0,SDK: 2.1.2

**Comment by mohuishou** [comment]
感谢你的建议，目前微信官方没有资讯相关的推送模板，所以暂时无法做到，如果有的话之后会加上的

**Comment by qianlongzt** [comment]
其实微信倒是有一个“学校通知”这个模板。

**Comment by mohuishou** [comment]
@qianlongzt 有么？没有看到诶
