### ISSUE TITLE
不及格成绩查询

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#433]
不及格的成绩查不到唉，是不是不希望我伤心呢

scuplus_version: 0.12.4
手机: HUAWEI-HWI-AL00-Android 8.0.0 
微信：6.6.7,SDK: 2.1.2

**Comment by mohuishou** [comment]
是的（其实是个bug）

**Comment by mohuishou** [comment]
bug修复了，等待微信审核中

**Comment by mohuishou** [comment]
已上线
