### ISSUE TITLE
关于成绩

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#434]
希望能开发成绩更新通知功能？万分感谢！总刷成绩好煎熬...

scuplus_version: 0.12.4
手机: HUAWEI-ALP-AL00-Android 8.0.0 
微信：6.6.6,SDK: 2.0.9

**Comment by mohuishou** [comment]
这个功能其实是有的哦，目前是每天早中晚系统会自动更新一次如果有更新会发送微信模板消息通知。但是如果在更新之前你自己刷到了就不会通知了，或者是7天内没有使用过小程序也没有办法发送通知
