### ISSUE TITLE
成绩查询显示“更新失败”

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#435]
最近多科期末成绩已出，已绑定，但刷新仍然显示“更新失败”，查不到成绩。

scuplus_version: 0.12.4
手机: HUAWEI-EVA-AL10-Android 7.0 
微信：6.6.7,SDK: 2.1.2

**Comment by mohuishou** [comment]
试试重新绑定一下教务处账号呢

**Comment by scuplus** [comment]
三个绑定都绑了

**Comment by scuplus** [comment]
也都重新绑过了

**Comment by mohuishou** [comment]
更新了成绩的返回机制，可以重新试试看

**Comment by mohuishou** [comment]
或者加一下qq群私聊一下群主莫回首吧，698433701

**Comment by scuplus** [comment]
好的，非常感谢，问题解决啦

**Comment by mohuishou** [comment]
解决了就好，这个问题关闭了哦
