### ISSUE TITLE
成绩计算

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#438]
等级为优秀良好等的成绩在教务系统的指导性教学计划里有准确的分数，目前好像是直接用一个固定值算的，会导致计算结果不准确呢

scuplus_version: 0.12.5
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 11.3.1 
微信：6.7.0,SDK: 2.1.2

**Comment by mohuishou** [comment]
这种情况的确是会不准确但是直接从指导性教学计划获取成绩有些麻烦，所以具体怎么改进还要考虑
