### ISSUE TITLE
一卡通掉卡补办候不更新

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#439]
补办了校园卡好像获取不到新卡的消费，消费记录已经静止了

scuplus_version: 0.12.5
手机: Xiaomi-MI 8-Android 8.1.0 
微信：6.6.7,SDK: 2.1.2

**Comment by mohuishou** [comment]
访问一下这个网站： ecard.scu.edu.cn 看看呢，We川大的数据是这上面获取的
