### ISSUE TITLE
[南鸢]: 不能绑定学号

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#44]
绑定学号时显示用户不存在或密码错误

scuplus_version: 0.5.3
手机: iPhone-iPhone 7 Plus<iPhone9,2>-iOS 11.2.1 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
注意绑定账号为统一认证中心的账号，不是教务处的密码

**Comment by mohuishou** [comment]
经过测试绑定账号是没有问题的，请你先到 my.scu.edu.cn 网站试试可以登陆不
