### ISSUE TITLE
课表太宽

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#440]
课表太宽，四天的课占了五天，不知道到底是哪几天上555，今天就是看了这个课表去上课，结果不用上。😭 

scuplus_version: 0.12.5
手机: xiaomi-Redmi Note 4X-Android 7.0 
微信：6.6.7,SDK: 2.1.2

**Comment by mohuishou** [comment]
很抱歉，因为We川大的bug让你白跑了，这个bug昨天其实已经修复了但是在等微信官方的审核

**Comment by mohuishou** [comment]
已修复
