### ISSUE TITLE
一卡通数据

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#441]
一卡通数据下拉之后还是没有显示数据。

scuplus_version: 0.12.5
手机: HUAWEI-EVA-AL00-Android 7.0 
微信：6.6.7,SDK: 2.1.2

**Comment by mohuishou** [comment]
因为访问不了http://ecard.scu.edu.cn 这个网站了，数据是从这个上面取的，一般过段时间就恢复了
