### ISSUE TITLE
课表信息错误

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#442]
这学期我发现有两门课的老师名字都与教务网对应不上。虽然没有什么大的影响，但我觉得这个bug还是应该给大佬们反馈一下。

scuplus_version: 0.12.6
手机: vivo-vivo X5S L-Android 4.4.4 
微信：6.6.7,SDK: 2.1.2

**Comment by mohuishou** [comment]
感谢你的反馈，具体是什么课程呢，希望反馈一下课程号，课序号，课程名，还有教务处上的老师名字谢谢

**Comment by scuplus** [comment]
（1）900001010    23    军事理论     教务网上为龚燕，we川大上是周凤 。                             （2）202028020     14    大学物理（理工）3 -2         教务网上为杨斌，we川大上是杨丽娟。

**Comment by mohuishou** [comment]
感谢你的支持，之后仔细排查一下

**Comment by mohuishou** [comment]
感谢你的反馈，已修复
