### ISSUE TITLE
收不到成绩通知

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#443]
出成绩以后没有收到小程序的通知

scuplus_version: 0.12.6
手机: HUAWEI-HUAWEI CRR-UL00-Android 6.0 
微信：6.6.1,SDK: 1.9.9

**Comment by mohuishou** [comment]
成绩通知要满足下面几个条件才可以哦
1. We川大会在每天早中晚三次更新成绩，如果在后台更新之前用户已经更新过了是没有通知的
2. 小程序通知需要用户7天以内使用过小程序
