### ISSUE TITLE
如何注销绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#447]
如何注销绑定

scuplus_version: 0.12.6
手机: iPhone-iPhone 7 Plus<iPhone9,2>-iOS 11.0.3 
微信：6.6.6,SDK: 2.0.9

**Comment by scuplus** [comment]
怎么修改😅

**Comment by mohuishou** [comment]
在个人中心教务处/图书馆/统一认证中心账号绑定的选项，选择对应的账号绑定就可以了
