### ISSUE TITLE
账号不存在

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#449]
已毕业登录不了账号了吗

scuplus_version: 0.12.6
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 12.0 
微信：6.7.0,SDK: 2.2.0

**Comment by mohuishou** [comment]
请先确认能否在学校相应的系统登录

**Comment by mohuishou** [comment]
先进学校官方网站尝试
