### ISSUE TITLE
一卡通余额没判断毕业情况

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#455]
我毕业了一卡通都被注册了，但是还是能查询出来余额，😄，感觉自己损失了一笔财富

scuplus_version: 0.12.8
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.3 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
暂时无法判断是否毕业
