### ISSUE TITLE
绩点计算

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#457]
可以选择对分数  属性进行排序吗？
感觉没有以前网页版好看

scuplus_version: 0.12.8
手机: vivo-vivo Xplay5A-Android 5.1.1 
微信：6.6.7,SDK: 2.2.2

**Comment by mohuishou** [comment]
小程序没有网页的功能多，所以要实现以前的界面麻烦了很多，之后会优化的
