### ISSUE TITLE
[Connie]: 课表的问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#46]
课表不能区别是否是本周的课程，全部都显示在课表里，有一点不方便，要是能改进就好了

scuplus_version: 0.5.3
手机: HUAWEI-HUAWEI CAZ-AL10-Android 6.0 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
课程表显示问题已经在开发计划当中了，0.6.0会解决这个问题

**Comment by mohuishou** [comment]
done，等待发布新版本
