### ISSUE TITLE
教务处绑定显示not found

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#468]
账号密码没问题。。。

scuplus_version: 0.12.8
手机: HUAWEI-PAR-AL00-Android 8.1.0 
微信：6.7.2,SDK: 2.2.4

**Comment by MengYa123** [comment]
因为教务系统更新了，所以应该好多东西的获取都要改

**Comment by MengYa123** [comment]
因为教务系统更新了，所以应该好多东西的获取都要改
