### ISSUE TITLE
无法绑定教务系统

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#478]
可以登进my.scu.edu.cn但是we川大上一直是not found，以前绑定过是对的，这次不知道是什么原因，删掉小程序再加入也不行

scuplus_version: 0.12.8
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.4.1 
微信：6.7.2,SDK: 2.2.4

**Comment by mohuishou** [comment]
教务处大更新，We川大还在适配中
