### ISSUE TITLE
获取课表显示空白

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#482]
无论获取什么时候的课表，总是空白一片，教务处已有本学期课表

scuplus_version: 0.12.8
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 11.4.1 
微信：6.7.2,SDK: 2.2.4

**Comment by mohuishou** [comment]
下拉刷新还是不行么？

**Comment by mohuishou** [comment]
bug原因已找到，等待微信审核中，感谢你的反馈

**Comment by mohuishou** [comment]
bug已修复下拉刷新即可

**Comment by scuplus** [comment]
问题解决啦，谢谢
