### ISSUE TITLE
学长，能进行广告合作吗

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#484]
学长，
就是进行app推广
怎样联系您呢
我是学弟qq809176942

scuplus_version: 0.12.8
手机: OPPO-OPPO R11-Android 7.1.1 
微信：6.7.2,SDK: 2.2.4

**Comment by mohuishou** [comment]
小程序最近要移交了，所以不接广告，新的小程序出来之后你可以添加QQ群找青创联的相关成员
