### ISSUE TITLE
程序的课程表功能

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#485]
表头星期几，是错的。。【1,1】表格显示的是星期三，实际上应该是星期日吧……

scuplus_version: 0.12.8
手机: Sony-G8342-Android 8.0.0 
微信：6.7.2,SDK: 2.2.4

**Comment by mohuishou** [comment]
bug已经修复，可以等新版本发布，或者点击清除缓存退出重新登录
