### ISSUE TITLE
快捷评教后仍无法获取成绩

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#486]
RT，快捷评教后查询成绩，显示“完成评估前无法获取成绩”，不知道是怎么回事？评估指的不是评教吗？

scuplus_version: 0.12.8
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.4.1 
微信：6.6.1,SDK: 1.9.9

**Comment by mohuishou** [comment]
登录教务处检查一下看看呢
