### ISSUE TITLE
[莫回首]: 反馈没有反馈通知

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#49]
当管理员回复反馈消息之后，加上反馈通知

scuplus_version: 0.5.3
手机: Xiaomi-Mi Note 3-Android 7.1.1 
微信：6.6.5,SDK: 1.9.91

**Comment by scuplus** [comment]
反馈评论测试   $$$莫回首

**Comment by mohuishou** [comment]
管理员回复测试

**Comment by scuplus** [comment]
反馈评论test   $$$莫回首

**Comment by mohuishou** [comment]
管理员回复测试
