### ISSUE TITLE
课表不能显示

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#490]
正确绑定教务处账号后，课表选择2018秋，刷新后显示不出来课表，多次尝试均是这样。望解决。

scuplus_version: 0.12.8
手机: OnePlus-ONEPLUS A6000-Android 8.1.0 
微信：6.6.7,SDK: 2.2.4

**Comment by mohuishou** [comment]
刚刚解决这个问题，退出重新进入然后下拉刷新试试呢？
