### ISSUE TITLE
一卡通无法绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#492]
一卡通更改过密码
通过we川大查询不了余额
且由于身份证号末位是X
即使未更改密码一卡通和教务处密码也不一致
始终无法绑定一卡通

scuplus_version: 0.12.8
手机: iPhone-iPhone X (GSM+CDMA)<iPhone10,3>-iOS 11.4.1 
微信：6.7.2,SDK: 2.2.4

**Comment by mohuishou** [comment]
密码是个人中心密码和教务处密码，一卡通密码是独立的

**Comment by scuplus** [comment]
所以是指用教务处密码就可以访问一卡通了吗
