### ISSUE TITLE
成绩等级与分数对应情况不符

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#500]
为什么成绩是A判定的是94呢？成绩单上我成绩是A分数是95.1，希望能够解答，谢谢~

scuplus_version: 0.12.8
手机: xiaomi-Redmi Note 4X-Android 7.0 
微信：6.7.2,SDK: 2.2.4

**Comment by mohuishou** [comment]
分数是直接从教务处获取的
