### ISSUE TITLE
课程表太难看了   没有以前整洁

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#501]
原先教务处的课程表手机一面可以清晰看到，现在的花花绿绿的又长

scuplus_version: 0.12.8
手机: HUAWEI-BAC-AL00-Android 8.0.0 
微信：6.7.2,SDK: 2.2.4

**Comment by mohuishou** [comment]
一面可以看到是很早之前的版本了，这个也是之前很多用户反馈左右滑动太麻烦才改的
