### ISSUE TITLE
控制台启动报错， 貌似是 eslint， 你们不报错吗？

### ISSUE THREAD

**Issue by feitian124** [mohuishou/scuplus-wechat#506]
项目下载下来，yarn install， yarn run dev，会报错，eslint 关掉貌似就可以了不报错。
eslint 不熟，但我不想关掉，请问 @mohuishou 您是怎么处理的，不报错吗？

···shell
λ yarn run dev
yarn run v1.10.1
$ wepy build --watch
[23:38:54] [编译] 入口: src\app.vue

E:\workspace-nodejs\scuplus-wechat\src\app.vue
  7:1  error  Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag

   5 | </style>
   6 |
>  7 | <script>
     | ^
   8 | import wepy from "wepy";
   9 | import "wepy-async-function";
  10 | import Http from "./util/http";

✖ 1 problem (1 error, 0 warnings)

[23:38:54] [写入] JSON: dist\app.json
[23:38:54] [编译] 组件: src\components\card.vue

E:\workspace-nodejs\scuplus-wechat\src\components\card.vue
  4:12  error  Parsing error: Unexpected token, expected }

  2 |   @border: 1px solid #eee;
  3 |   .icon(@size, @font-size, @background) {
> 4 |     display: flex;
    |            ^
  5 |     justify-content: center;
  6 |     align-items: center;
  7 |     width: @size;

✖ 1 problem (1 error, 0 warnings)

···

**Comment by mohuishou** [comment]
eslint错误不影响程序运行，所以暂时没管

**Comment by feitian124** [comment]
ok, 谢谢，我还以为我环境哪里有问题
