### ISSUE TITLE
貌似服务器过期了

### ISSUE THREAD

**Issue by LIlGG** [mohuishou/scuplus-wechat#508]
使用的时候调用接口出现 
### {"error":{"name":"usageLimitError","message":"Usage limit reached. Contact your team admin."}}.
是什么原因

**Comment by mohuishou** [comment]
这个是postman的mock服务，可以直接点run postman即可，目前被调用的太多了

**Comment by LIlGG** [comment]
嗯嗯 问题已经解决了。非常感谢
