### ISSUE TITLE
[Totoro]: 课程

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#51]
希望可以找到别的课的时间表，能去蹭课，谢谢(｡’▽’｡)♡

scuplus_version: 0.5.3
手机: Meizu-m3 note-Android 5.1 
微信：6.6.1,SDK: 1.9.9

**Comment by mohuishou** [comment]
下一版本主要优化资讯页面，这个功能添加到之后的版本计划当中了，感谢你的建议
