### ISSUE TITLE
编译出错，不知道怎么解决，求解

### ISSUE THREAD

**Issue by zhanghonggang** [mohuishou/scuplus-wechat#510]
Error: eslint-plugin-html error: It seems that eslint is not loaded.

**Comment by mohuishou** [comment]
yarn 试试？看起来应该是依赖问题

**Comment by zhanghonggang** [comment]
![image](https://user-images.githubusercontent.com/50233099/69692942-a396ba00-110e-11ea-950d-e2795c1cdf6f.png)
还是一样的原因，我是环境出问题了吗

**Comment by zhanghonggang** [comment]
尝试了下yarn,确实解决了这个问题，但是编译又报出新的错误，查阅了下 好像并不是js关键字，还有终端
![image](https://user-images.githubusercontent.com/50233099/69697988-0ee88800-111f-11ea-94b7-f58dc3d8d42a.png)很多error，我想应该是eslint-plugin-vue检查的结果，但我并不知道怎么解决

**Comment by zhanghonggang** [comment]
![image](https://user-images.githubusercontent.com/50233099/69698119-6a1a7a80-111f-11ea-8618-d26225002e3c.png)
感谢大佬，通过yarn下载确实解决了这个问题，但是运行编译又报错如图，还有终端的检查error，我想大概是eslint-plugin-vue的锅，但我并不知道怎么解决

**Comment by mohuishou** [comment]
这个需要关掉 vscode 的 eslint 语法检查，因为 wepy 1 和 vue 的语法还是不一样的

**Comment by zhanghonggang** [comment]
已解决，感谢大佬

**Comment by mohuishou** [comment]
客气了，close
