### ISSUE TITLE
Uncaught TypeError: Cannot set property 'Promise' of undefined

### ISSUE THREAD

**Issue by zhanghonggang** [mohuishou/scuplus-wechat#511]
![image](https://user-images.githubusercontent.com/50233099/69767888-4572e100-11b9-11ea-90a1-3b02a36090bd.png)
![image](https://user-images.githubusercontent.com/50233099/69767993-aef2ef80-11b9-11ea-8c28-405a0bc3bb13.png)
尝试将前端包导入微信小程序，发现以下错误，后端运行好像少了文件（没学过go  所以不太清楚），迫于毕业设计，还请大佬原谅我这些常识性错误😭

**Comment by mohuishou** [comment]
不要 go mod vendor ，直接执行即可，这个有点问题，还没来得及改
