### ISSUE TITLE
编译试了两个环境都不行

### ISSUE THREAD

**Issue by chenxuezhou** [mohuishou/scuplus-wechat#512]
/root/scuplus-wechat/node_modules/eslint/lib/config/plugins.js:120
                throw pluginLoadErr;

另一个环境报错就不发了

好坑 @mohuishou

**Comment by lvyunze** [comment]
![image](https://user-images.githubusercontent.com/37875663/81479448-bd0f6680-9255-11ea-93ab-a889b3c864c6.png)
然后重新install，最后缺啥就单独install啥

**Comment by mohuishou** [comment]
fix https://github.com/mohuishou/scuplus-wechat/commit/e7be12ac5e42a4ffe618fd202e5ac56d3782a2f0
