### ISSUE TITLE
[yoosu_]: 希望添加一个校车时刻表功能

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#52]
感觉添加一个校车时刻表功能会更好呢～谢谢啦

scuplus_version: 0.5.3
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 10.3.3 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
这个在下一版本会添加上，感谢你的建议

**Comment by mohuishou** [comment]
已经更新了，请后台删除小程序进程重新进入体验。
新增校车时刻表
修复校历周次bug
绩点计算器新增选择所有必修课成绩
图标修改为全局引入

**Comment by scuplus** [comment]
哇，太棒了吧！没想到这么好！！！   $$$yoosu_

**Comment by scuplus** [comment]
哇，太棒了吧！没想到这么好！！！   $$$yoosu_

**Comment by mohuishou** [comment]
提前更新了小版本，如果觉得不错的话就分享给同学帮忙宣传宣传吧，谢谢。
