### ISSUE TITLE
[歪着头拯救世界]: 主题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#55]
能不能多几种颜色的主题，比如和少女粉对应的直男黑

scuplus_version: 0.5.3
手机: OPPO-OPPO R9 Plustm A-Android 5.1.1 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
这个可以有，但是要放到后面了，目前主要精力还是先实现功能
