### ISSUE TITLE
[Darcy]: 课表显示不完整

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#57]
课表显示不完整

scuplus_version: 0.5.3
手机: Xiaomi-MI MAX 2-Android 7.1.1 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
课表目前只显示当前周次的课表，可以调整周次切换，如果是同一时间有两门课程，现在暂时不支持，如果不是以前情况请发送邮件附带截图到1@laillin.xyz谢谢

**Comment by scuplus** [comment]
抱歉，邮件发送不成功，提示无此邮箱，请问邮箱是否正确。1@laillin.xyz   $$$Darcy

**Comment by mohuishou** [comment]
不好意思刚刚手机打字打错了，1@lailin.xyz

**Comment by scuplus** [comment]
邮件已发送，请查收(´ . .̫ . `)   $$$Darcy

**Comment by mohuishou** [comment]
感谢你的反馈，问题排查中

**Comment by mohuishou** [comment]
已修复，请进入课表下拉刷新查看

**Comment by scuplus** [comment]
好的。(´ . .̫ . `)谢谢   $$$Darcy

**Comment by mohuishou** [comment]
问题关闭了，感谢你的使用
