### ISSUE TITLE
教务处账号无法绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#58]
点击绑定没有反应

scuplus_version: 0.3.0
手机: Meizu-MX5-Android 5.1 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
你好，绑定账号为统一认证账号而不是教务处，为my.scu.edu.cn的账号密码，如果显示绑定教务处，那么请在后台关闭小程序从微信从新进行更新新版小程序
