### ISSUE TITLE
[桃下]: 用户不存在？

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#59]
学号正确密码正确 就是绑定不了

scuplus_version: 0.5.3
手机: iPhone-iPhone 6 Plus<iPhone7,1>-iOS 11.2.6 
微信：6.6.3,SDK: 1.9.91

**Comment by mohuishou** [comment]
请确认你输入的是统一认证中心(my.scu.edu.cn)的账号密码，而不是教务处的，如果显示绑定教务处账号，请在后台关闭小程序，然后重新进入绑定
