### ISSUE TITLE
[犹伟]: 关于必修计算

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#60]
成绩查询里面建议增加一个选择全部必修的按钮

scuplus_version: 0.5.3
手机: xiaomi-MI 5X-Android 7.1.2 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
之前没有加这个的原因是考虑到，全部必修成绩已经计算出来了，可以考虑之后加上

**Comment by scuplus** [comment]
有的人中华文化显示的是选修，但实际上有的学院必须要加上中华文化算平均成绩，一个个点太麻烦了   $$$犹伟

**Comment by mohuishou** [comment]
是这样啊。好的，谢谢你的反馈

**Comment by mohuishou** [comment]
已经更新了，请后台删除小程序进程重新进入体验。
新增校车时刻表
修复校历周次bug
绩点计算器新增选择所有必修课成绩
图标修改为全局引入

**Comment by scuplus** [comment]
好的，谢谢   $$$犹伟

**Comment by scuplus** [comment]
图书馆网址还是不能访问么？   $$$犹伟

**Comment by mohuishou** [comment]
刚刚试了一下还是不行，主要是学校的my.scu.edu.cn无法跳转过去，单独绑定账号会把问题复杂化，暂时观望一下吧
