### ISSUE TITLE
[皂菌是也]: 校历

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#61]
校历的周数有问题吧，第一周应该是4号那周吧(｢･ω･)｢嘿

scuplus_version: 0.5.3
手机: HONOR-KNT-AL10-Android 7.0 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
的确是的，谢谢你的反馈，目前校历不能自动刷新数据，这个在下一版本修复

**Comment by scuplus** [comment]
好的~   $$$皂菌是也

**Comment by mohuishou** [comment]
已经更新了，修复了这个bug，请后台删除小程序进程重新进入体验。
新增校车时刻表
修复校历周次bug
绩点计算器新增选择所有必修课成绩
图标修改为全局引入
