### ISSUE TITLE
[翩翩精品 E=mc²]: 对对对

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#62]
反反复复方法

scuplus_version: 0.5.3
手机: Xiaomi-Redmi 3-Android 5.1.1 
微信：6.6.5,SDK: 1.9.91

**Comment by scuplus** [comment]
test 建议删除   $$$翩翩精品 E=mc²

**Comment by mohuishou** [comment]
请不要随意发送无用反馈，done
