### ISSUE TITLE
[翩翩精品 E=mc²]: 能大概讲一下we川大和后台服务器的信息交互过程吗？

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#63]
你好，我在wepy下看到您的小程序的 请问能讲下小程序额和您的后台服务器的通讯过程吗？比如说怎么绑定账号？以及后台服务器的数据库设计？非常感谢！！！

scuplus_version: 0.5.3
手机: Xiaomi-Redmi 3-Android 5.1.1 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
这么多。。。

通信直接就是api交互，用户省份鉴定用jwt，绑定账号只需要用一个字段记录一下是否绑定没有绑定前端自动跳转到绑定页面就可以了。
详细的API考虑会在功能稳定之后整理一份出来，便于快速搭建自己学校的小程序

**Comment by mohuishou** [comment]
ok，关闭问题了
