### ISSUE TITLE
[Amour]: 用户不存在

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#64]
输入了从小到大所有用过的密码，还是不存在，你还要我怎样QAQ

scuplus_version: 0.5.3
手机: Xiaomi-MI 6-Android 7.1.1 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
我也很绝望，请尝试先登录 my.scu.edu.cn ，这个网站可以登录了，就可以了。如果还是不行，在这个网站上面可以重置密码，谢谢
