### ISSUE TITLE
[当海不蓝]: 课程信息不全

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#66]
选的网课隔周上的课程表上没有添加

scuplus_version: 0.5.3
手机: Xiaomi-Redmi 4-Android 6.0.1 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
课表目前只显示当前周次的课表，可以调整周次切换，如果是同一时间有两门课程，现在暂时不支持，如果不是以前情况请发送邮件附带截图到1@lailin.xyz谢谢
