### ISSUE TITLE
我正在学习，但是你的文件为什么都是.vue我怎么才能把他们改为正常的？

### ISSUE THREAD

**Issue by dkh1234** [mohuishou/scuplus-wechat#68]
刚开始学习前端

**Comment by mohuishou** [comment]
不知道你说的正常的是什么，html?js?，这个项目用的是wepy框架，用的是类vue的语法，如果你说的是.wpy的话没有影响，只是扩展名换了。如果不是的话建议你先看看https://github.com/Tencent/wepy

**Comment by dkh1234** [comment]
十分感谢您耐心的回复，
我是想说.vue用啥打开，怎样才能用微信开发工具打开！

**Comment by mohuishou** [comment]
用一般的编辑器打开，vscode,atom,sublime之类的都可以，不用微信和编辑器，微信开发者工具只用来预览
