### ISSUE TITLE
[麦冬]: 课表增加蹭课添加功能

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#69]
可以像超级课程表一样，编辑自己的课表，把自己想要去听的蹭课也加进去就好了～

scuplus_version: 0.5.3
手机: HONOR-PRA-AL00-Android 7.0 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
good idea。但是短期内还没有精力去实现，这个idea的排期要稍微往后一点。感谢您的反馈
