### ISSUE TITLE
[当海不蓝]: 课表格子大小

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#71]
强烈建议改下课表格子的宽度，然后屏幕就能放下周一到周五的课了

scuplus_version: 0.5.3
手机: Xiaomi-Redmi 4-Android 6.0.1 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
其实第一版本就是这样的，但是宽度小了之后，课程名比较长的课程显示会有问题，现在的宽度是经过权衡的。
视野问题目前进入课程表都会跳转到当天的课程。
感谢你的建议，如果有了好的实现方案会进行调整的
