### ISSUE TITLE
[阿焕]: 你好，为什么我输入学号以后显示用户不存在

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#72]
我输入学号以后显示用户不存在，我是17级的

scuplus_version: 0.5.3
手机: samsung-SM-N9005-Android 5.0 
微信：6.6.1,SDK: 1.9.9

**Comment by mohuishou** [comment]
你好请使用my.scu.edu.cn的密码登录。先尝试一下登录这个网站。不是教务处的账号密码
