### ISSUE TITLE
[李白]: 课程表显示有问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#73]
有的课没显示 有的课显示多了

scuplus_version: 0.5.3
手机: iPhone-iPhone SE<iPhone8,4>-iOS 11.3 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
请问具体是什么课程呢，课表目前只显示当前周次的课表，可以调整周次切换，如果是同一时间有两门课程，现在暂时不支持，如果不是以前情况请发送邮件附带截图到1@lailin.xyz谢谢
