### ISSUE TITLE
[青蛙蛙]: info和教务处的内容没有更新哦

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#74]
加油！

scuplus_version: 0.5.3
手机: Xiaomi-MIX 2-Android 8.0.0 
微信：6.6.5,SDK: 1.9.91

**Comment by mohuishou** [comment]
感谢你的反馈，新版本会解决这个问题，并且会带来史上最全的川大资讯集合，第一期包括了15个左右的校级机构以及学院官网资讯信息。新版本应该会在本周完成发布

**Comment by scuplus** [comment]
666，加油加油，给大佬打call   $$$青蛙蛙

**Comment by IanSmith123** [comment]
教务处在上学期期末增加了反爬虫机制，目前尝试可用的方法是headless, 另外phantomjs似乎并不可行,如果你对也有研究的话可以交流一下。

**Comment by mohuishou** [comment]
@IanSmith123 谢谢你的提醒，反爬虫机制的问题之前已经解决了，而且不止教务处，目前至少碰到了四个学校相关网站有反爬虫机制，还专门写过一篇博客，http://lailin.xyz/post/%E4%BD%BF%E7%94%A8chromedp%E8%A7%A3%E5%86%B3%E5%8F%8D%E7%88%AC%E8%99%AB%E9%97%AE%E9%A2%98/

**Comment by mohuishou** [comment]
新版本已更新

**Comment by IanSmith123** [comment]
我也不是很懂他的反爬虫的机制，没分析出来他的cookie是怎么生成的，用了浏览器的什么特性。似乎他还干掉了phantomjs, 另：我的解决[方法](https://les1ie.com/2018/03/15/anti-anti-spider/)
