### ISSUE TITLE
[古月]: 运行略卡，有些数据需要长久刷新

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#75]
运行略卡，有些数据需要长久刷新

scuplus_version: 0.7.0
手机: HUAWEI-HUAWEI VNS-TL00-Android 6.0 
微信：6.6.1,SDK: 1.9.9

**Comment by mohuishou** [comment]
这个是数据渲染的问题，这个问题会慢慢优化的，感谢你的关注，如果觉得还不错，分享到朋友圈或者微信群吧
