### ISSUE TITLE
一卡通背景图

### ISSUE THREAD

**Issue by IanSmith123** [mohuishou/scuplus-wechat#76]
程序里面使用的图片
![](https://scuplus.oss-cn-shenzhen.aliyuncs.com/ecard/1.jpg)
也就是这里的第一张
![](https://raw.githubusercontent.com/mohuishou/scuplus-wechat/2b4218d19cd7c6e26549bbbc307b5c74a6a0d33c/img/preview.jpg)
 似乎是用的[这里](https://zhuanlan.zhihu.com/p/28861952)的图片，但是询问了下作者他似乎对此并不知情，希望能和作者沟通一下 🤷‍♂️

**Comment by mohuishou** [comment]
的确欠妥了，谢谢提醒

**Comment by IanSmith123** [comment]
知乎私信或者info的tg应该可以找到他 😃

**Comment by mohuishou** [comment]
私信过了0.0
