### ISSUE TITLE
[Wizard Huang]: 课程不全

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#79]
坚果pro2课程缺少

scuplus_version: 0.7.0
手机: SMARTISAN-OS105-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
课表目前只显示当前周次的课表，可以调整周次切换，如果是同一时间有两门课程，现在暂时不支持，如果不是以上情况请发送邮件附带截图到1@lailin.xyz谢谢
