### ISSUE TITLE
[]: 小bug，用户体验感考虑不周全

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#81]
小bug：新闻部分页面最后面是原文地址链接，但被转发和分享按钮遮住，无法复制或者点击，则无法进入原网站进行附件的下载。

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s Plus<iPhone8,2>-iOS 10.3.3 
微信：6.6.1,SDK: 1.9.9

**Comment by mohuishou** [comment]
感谢您的反馈，这个问题是由于不同机型的差异造成的，下个版本会修复
