### ISSUE TITLE
[曾宇哲zzZ]: 麻烦换个颜色…

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#85]
麻烦换个颜色或者增加个皮肤选择…男生有点受不了粉色

scuplus_version: 0.7.0
手机: iPhone-iPhone 6s<iPhone8,1>-iOS 11.0 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
下个版本会优化这个问题，感谢你的反馈
