### ISSUE TITLE
[米丝某洁]: 资讯界面交互建议

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#86]
切换栏目只能点标签有点麻烦，能左右滑动换栏目更好。

scuplus_version: 0.7.0
手机: Xiaomi-MI 5s-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
以前是可以左右滑动的，但是添加的标签选择之后，左右滑动目前还有bug，只能暂时下线，后面优化好了会重新下线的，感谢你的反馈，可以添加用户qq群：698433701

**Comment by scuplus** [comment]
加油！   $$$米丝某洁
