### ISSUE TITLE
[我家呆妹]: 自习

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#87]
自习界面能加一个调日期的么，比如我今晚想看明天的空闲教室，或者看后天的教室。

scuplus_version: 0.7.0
手机: Hisense-Hisense F30-Android 6.0 
微信：6.6.3,SDK: 1.9.5

**Comment by mohuishou** [comment]
这个功能暂时不行，后面看一下学校有没有相关的查询界面，才能看能不能做，现在的自习是实时的
