### ISSUE TITLE
[温酒]: 界面颜色

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#89]
可以选蓝色或者自己自行选择颜色吗，粉色太辣眼睛了

scuplus_version: 0.7.0
手机: iPhone-iPhone 7 Plus<iPhone9,2>-iOS 11.2.6 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
下个版本会优化这个问题

**Comment by mohuishou** [comment]
感谢你的反馈

**Comment by scuplus** [comment]
晚安ʕ •ᴥ•ʔ   $$$温酒
