### ISSUE TITLE
[F7]: 账号绑定

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#90]
账号绑定后点击账号绑定应该显示学号名字什么的，而不是重复绑定界面

scuplus_version: 0.7.0
手机: HONOR-DUK-AL20-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢您的反馈，账号绑定页面的优化已经在下个小版本排期了
