### ISSUE TITLE
[青蛙蛙]: 来反馈出现的问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#91]
我的手机打开we川大首页会出现一个哭丧的脸，在qq群里已经提到过了

scuplus_version: 0.7.0
手机: Xiaomi-MIX 2-Android 8.0.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
疑难杂症，排查中..

**Comment by mohuishou** [comment]
已修复
