### ISSUE TITLE
[bounty bounty]: 校历

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#93]
建议校历上能标注学期当然周数，相应的节假日标红。

scuplus_version: 0.7.0
手机: OPPO-OPPO A79-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
感谢你的反馈，校历目前已经支持周数和事件显示，节假日标红，需要后期再完善一下，可以添加用户qq群: 698433701

**Comment by scuplus** [comment]
这个群主要是来干什么的？   $$$bounty bounty

**Comment by mohuishou** [comment]
(⊙o⊙)…，用户反馈群，当然也可以水

**Comment by scuplus** [comment]
想问校园卡流水只支持三天的查询吗 -_-   $$$bounty bounty

**Comment by mohuishou** [comment]
其实并不是，校园卡页面后面一两个版本会进行重构，到时候就可以查询所有的流水了
