### ISSUE TITLE
[无名英雄kzh]: 校内导航

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#95]
可以添加校内导航功能，方便定位一些不常去的地方(工程训练中心，学子书店，望江各种食堂等)

scuplus_version: 0.7.0
手机: Honor-SCL-TL00-Android 5.1.1 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
(⊙o⊙)…这是个好主意，不错排期稍微靠后哦
用户qq群: 698433701
