### ISSUE TITLE
[周周]: 账号绑定不了

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#96]
账号显示绑定成功，但是主页却没有任何消息，总得说就是绑定不成账号

scuplus_version: 0.7.0
手机: OPPO-OPPO R11-Android 7.1.1 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请退出小程序（后台关闭）然后再试试呢？目前的确有一定几率出现这个bug 
可以添加用户交流、反馈群: 698433701
