### ISSUE TITLE
[南楠]: 关于个人隐私保护问题

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#97]
账号绑定密码是身份证后六位，但是身份证号学校统计过多次，这个数据经了很多人的手，不安全性可想而知。因此有人会修改校园卡、教务系统、体育处网站等账号的密码(，但是！今天我只输了身份证后六位，居然所有的信息都能看到？？？？？？
当时心里真的惊呆了，这个绑定密码怎么修改？？？？？

scuplus_version: 0.7.0
手机: Xiaomi-MI 5s-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
你好，这个密码不是we川大可以控制的，是统一认证中心的账号密码，密码修改请网页访问 my.scu.edu.cn 。
感谢你的提醒，用户的密码是加密过后保存的，后台的数据安全会尽最大的努力去保证。
可以添加用户交流、反馈群: 698433701
