### ISSUE TITLE
[逐影追星]: 无个人信息

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#98]
绑定账号成功后，没有查看到个人信息(课表等)

scuplus_version: 0.7.0
手机: HUAWEI-VTR-AL00-Android 7.0 
微信：6.6.5,SDK: 1.9.97

**Comment by mohuishou** [comment]
请退出小程序（后台关闭）然后再试试呢？目前的确有一定几率出现这个bug
可以添加用户交流、反馈群: 698433701
