### ISSUE TITLE
[🎶]: 研究生没有信息？

### ISSUE THREAD

**Issue by scuplus** [mohuishou/scuplus-wechat#99]
如题

scuplus_version: 0.7.0
手机: iPhone-iPhone 7<iPhone9,1>-iOS 11.2.5 
微信：6.6.3,SDK: 1.9.97

**Comment by mohuishou** [comment]
没有研究生的测试账号，所以暂时没有办法开发。不过资讯信息已经添加研究生学院的了
可以添加用户交流、反馈群: 698433701
